Class {
	#name : #GtCrasherGeneratedAKA,
	#superclass : #Object,
	#instVars : [
		'edxqpwir',
		'atxscxm',
		'jlyfrz',
		'przagrpbvdcu',
		'lezrme',
		'oeezsmfathgyz',
		'hlffhjvq',
		'bmlnkbmxsxuab',
		'ybnqecsnnniza',
		'dkrugmrwtd',
		'vvfodzdnwy',
		'nmcdiqnpgeno',
		'hcmjavpldpc',
		'poimsfh',
		'ouzloaexknuzjy',
		'qeehzubcvehbo',
		'ubzfsqazctqn',
		'zosebyzlkjflf'
	],
	#category : #'GToolkit-CrasherGenerated'
}

{ #category : #'baseline 1.0' }
GtCrasherGeneratedAKA >> bcjxbpJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq."
	^ #[90 84 215 8 234 2 110 193 166 208 185 75 82 95 1 241 200 41 61 200 41 174 119 6 251 133 92 227 168 122 139 155 247 85 70 194 221 106 156 173 171 92 111 131 196 136 147 244 11 2 248 52 72 146 49 248 147 29 118 4 46 67 195 65 3 33 160 230 250 102 180 122 80 19 2 93 152 175 111 240 48 235 182 108 40 138 219 68 244 129 40 71 152 1 238 137 233 238 97 137 86 103 199 155 243 165 167 135 226 239 111 152 99 192 132 146 60 35 114 3 88 10 81 97 125 121 74 195 75 15 81 174 82 71 33 108 2 202 8 96]
]

{ #category : #'private-class var' }
GtCrasherGeneratedAKA >> budbilseeqjAT [
	"Lorem ipsum dolor sit amet, consectetur adip."
	^ #dkfqthwsamogayijjruamulidsfwyvqvzcrkhoivzkitezj
]

{ #category : #'open changes' }
GtCrasherGeneratedAKA >> budbilseeqjD [
	^ #bkstdkwqvbsnpnbksrpquwflsqusqpktzjgj
]

{ #category : #'old api' }
GtCrasherGeneratedAKA >> clmluusopxdkiK [
	^ atxscxm
]

{ #category : #'accept/cancel' }
GtCrasherGeneratedAKA >> eqtaviuogtAK [
	^ #[253 242 143 8 30 165 146 62 74 6 136 17 46 65 213 101 247 93 74 1 83 37 157 108 241 101 226 176 135 131 78 73]
]

{ #category : #'protocol-shortcuts' }
GtCrasherGeneratedAKA >> eqtaviuogtAO [
	^ jlyfrz
]

{ #category : #'tests - working' }
GtCrasherGeneratedAKA >> eqtaviuogtO [
	"Lorem ipsum dolor sit amet, consectetur."
	^ #swxjdvnzlhrga
]

{ #category : #'accessing cursor' }
GtCrasherGeneratedAKA >> eqtaviuogtW [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini."
	^ #osyrczzketxviwiqnxfdwtekwgrjeor
]

{ #category : #'refactoring support' }
GtCrasherGeneratedAKA >> gpimjabqlmG [
	^ ubzfsqazctqn
]

{ #category : #'tests-collections' }
GtCrasherGeneratedAKA >> gpimjabqlmP [
	"Lorem ipsum dolor sit amet, consectetur adipis."
	^ #[140 34 153 206 96 124 228 126 131 10 66 11 204 186 61 19 8 237 19 198 115 100 131 105 190 198 87 5 65 185 207 30 229]
]

{ #category : #basic }
GtCrasherGeneratedAKA >> gsonvcbhllxmI [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Pariatur proident velit quis exercitation est dolore culpa in ea dolore elit duis ad in ut. In in adipiscing. 

Cillum nostrud do.'
]

{ #category : #'test addition' }
GtCrasherGeneratedAKA >> gsonvcbhllxmY [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sunt dolore proident cupidatat ex magna veniam ut veniam adipiscing et. Enim occaecat proident cillum eiusmod ut. Mollit id et voluptate. Voluptate fugiat amet fugiat reprehenderit irure et do quis ut adipiscing pariatur cillum adipiscin.'
]

{ #category : #'tests - operations on categories' }
GtCrasherGeneratedAKA >> gyzwpyycyAM [
	^ oeezsmfathgyz
]

{ #category : #'menu - operations' }
GtCrasherGeneratedAKA >> gzdillrdvwfqmjfF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod t."
	^ #rafphmgfhiyamrgmuxoswclnekqzvmkmzscql
]

{ #category : #combining }
GtCrasherGeneratedAKA >> hsmyqaaofsB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerc."
	^ #[114 166 208 39 155 200 91 216 238 236 38 132 204 124 125 89 113 153 81 239 217 182 146 104 150 251 254 199 109 108 37 66 198 156 164 154 134 44 238 164 179 203 125 75 1 145 29 72 1 156 237 200 14 202 102 141]
]

{ #category : #setUps }
GtCrasherGeneratedAKA >> hsmyqaaofsL [
	^ #oktjnaztmlthwcnvwhvzubcjlktjsukqpafoxkaewlvhepp
]

{ #category : #dispatching }
GtCrasherGeneratedAKA >> ilofzaadAJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve."
	^ qeehzubcvehbo
]

{ #category : #'test alpha/numeric version numbers' }
GtCrasherGeneratedAKA >> jzzugerfskbhmAF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun."
	^ #gkusrbgopafruoeddiytuulqeiiilaqtalprr
]

{ #category : #housekeeping }
GtCrasherGeneratedAKA >> jzzugerfskbhmAN [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis.'
]

{ #category : #'stream protocol' }
GtCrasherGeneratedAKA >> ktcmhaauvylAA [
	^ #venhbjlhechmwciguxxuy
]

{ #category : #'private - crlf' }
GtCrasherGeneratedAKA >> ktcmhaauvylS [
	"Lorem ipsum dolor sit amet, consectetur adi."
	^ ubzfsqazctqn
]

{ #category : #iteration }
GtCrasherGeneratedAKA >> ktcmhaauvylX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore m."
	^ #blxtgulreyibassbtnzesdajrecfrxvatnkhhywilbrkrsb
]

{ #category : #'tests - Class Methods' }
GtCrasherGeneratedAKA >> lzivergntbeoR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud."
	^ ouzloaexknuzjy
]

{ #category : #'tests - scrolling' }
GtCrasherGeneratedAKA >> nyulznzxyH [
	^ przagrpbvdcu
]

{ #category : #'testing-empty' }
GtCrasherGeneratedAKA >> onyxtiA [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerci.'
]

{ #category : #'dictionary access' }
GtCrasherGeneratedAKA >> onyxtiAB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Amet elit proiden.'
]

{ #category : #'tests - conversion' }
GtCrasherGeneratedAKA >> onyxtiQ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ven."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Deserunt dolor sit eu non dolor sint. Occaecat ea commodo ex duis aliqua reprehenderit elit esse do veniam. Sit deserunt culpa incididunt exercitation culpa tempor officia ut irure. Nisi aute cupidatat deserunt. 

Amet eiusmod. Aliqua culpa nulla esse officia qui dolore eiusmod esse adipiscing. 

Veniam eu nulla non nisi sint occaecat ut nulla pariatur ad.'
]

{ #category : #'services menu' }
GtCrasherGeneratedAKA >> pooignigiqzwfAP [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Tempor sunt exercitation ut cillum aliqua sed culpa veniam aliquip duis. Elit adipiscing commodo in ul.'
]

{ #category : #conversion }
GtCrasherGeneratedAKA >> pooignigiqzwfAR [
	^ #urmdmubmqzaaunoamwwtcryyamzhxwchmwulzfqcubjr
]

{ #category : #'test slice' }
GtCrasherGeneratedAKA >> pxvkdsgzpudzyAC [
	^ hlffhjvq
]

{ #category : #nodes }
GtCrasherGeneratedAKA >> pxvkdsgzpudzyU [
	^ #jcnafdmpeiqegigqflehjmwwpcniboazcuyesdszsscwfey
]

{ #category : #'cubic support' }
GtCrasherGeneratedAKA >> qtguacrahsxAV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Nisi dolore voluptate dolore officia pariatur. Irure minim cupidatat mollit nisi esse consequat elit eu sint commodo eu cillum irure nisi sit excepteur occaecat laborum elit. Cillum officia. Minim irure pariatur proident laborum. Irure eiusmod consequat aute culpa reprehenderit in in officia nulla elit. Adipiscing ut laboris ad ullamco velit. Incididunt ut ut anim dolo.'
]

{ #category : #descriptions }
GtCrasherGeneratedAKA >> qylerrxalqtvfqxAU [
	^ atxscxm
]

{ #category : #'test registration' }
GtCrasherGeneratedAKA >> qylerrxalqtvfqxV [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .'
]

{ #category : #'tests - as sorted collection' }
GtCrasherGeneratedAKA >> rkusjpwofubpvutT [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Voluptate consectetur aliquip magna id quis dolor ea ullamco quis aliquip. Culpa sunt culpa quis officia. Minim aute lorem in culpa dolor labore sint cillum ea. In id amet aute anim. Labore occaecat sunt dolor velit occaecat reprehenderit esse eiusmod. In aliqua officia laboris est est consequat nostrud officia. 

Lorem ipsum dolor sit amet, consectetur adipiscing.'
]

{ #category : #'tests - ScaledDecimal' }
GtCrasherGeneratedAKA >> smlawslmtbloAD [
	^ bmlnkbmxsxuab
]

{ #category : #profiling }
GtCrasherGeneratedAKA >> smlawslmtbloAE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
	^ #[126 251 229 242 173 199 243 79 180 125 164 164 2 179 159 28 52 89 55 98 246 200 234 83 193 37 77 99 172 154 140 94 47 227 205 252 16 207 184 86 38 102 148 34 162 174 87 212 237 33 22 88 248 138 151 29 180 1 29 62 141 175 231 224 20 209 61 126 161 222 93 74 16 254 209 191 130 80 77 127 174 118 87 128 13 61 93 168 91 117 41 177 227 143 112 93 163 117 210 233 94 225 137 180 178 21 221 236 74 164 76 157 140 51 149 146 237 141 114 219 58 107 6 249 124 235 150 131 74 33 66 245 80 187 236 86 17 219 246 13 215 10 156 183 156 104 181 151 155 8 22 230 196 112 138 197 143 41 27 184 4 78 129 137 231 190]
]

{ #category : #'character writing' }
GtCrasherGeneratedAKA >> smlawslmtbloAH [
	"Lorem ipsum dolor sit amet, consectetur."
	^ #[228 139 224 6 75 205 5 226 187 4 143 52 36 253 215 154 170 147 191 124 167 62 231 216 191 57 187 231 156 151 49 138 96 254 20 225 197 35 43 144 83 196]
]

{ #category : #'test - unlimited ivars' }
GtCrasherGeneratedAKA >> smlawslmtbloAS [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad."
	^ #szrbchybvyjsndpwclvkmieavrtdlnjwgsqmckdmiq
]

{ #category : #MonticelloGUI }
GtCrasherGeneratedAKA >> smlawslmtbloN [
	^ #pvfbnmnenwylkawdjjvxbtzfhniqjnvwzp
]

{ #category : #'testing - temp access' }
GtCrasherGeneratedAKA >> tlimhfvupwvAI [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud e."
	^ przagrpbvdcu
]

{ #category : #'protected low level' }
GtCrasherGeneratedAKA >> udymanbjcsE [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Voluptate qui eiusmod nulla id. Voluptate adipiscing do est ad esse pariatur ipsum dolore elit sed veniam nisi ea velit sint. Dolore id ullamco do. Consectetur do ea nisi dolor ut dolor non voluptate id ipsum eiusmod qui dolor exercitation aute laboris duis lorem. Id mollit ullamco dolor lorem in non enim ex proident incididunt laborum minim proident.'
]

{ #category : #'popup - opening dispatch' }
GtCrasherGeneratedAKA >> vcygctiqewAQ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi u."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

In aliquip aute occaecat fugiat in reprehenderit dolore voluptate mollit veniam dolor. Cillum veniam.'
]

{ #category : #rewriting }
GtCrasherGeneratedAKA >> vezkamirC [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea c.'
]

{ #category : #'running-remove actions' }
GtCrasherGeneratedAKA >> vezkamirM [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Eiusmod consectetur amet veniam esse occaecat officia cupidatat dolore. Duis culpa fugiat duis in reprehenderit consequat. 

Ex ullamco tempor in est. 

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a.'
]

{ #category : #'public api' }
GtCrasherGeneratedAKA >> wqbyvuknkrnjezrAG [
	^ hlffhjvq
]

{ #category : #'access options' }
GtCrasherGeneratedAKA >> yaqimgpzsjnygpAL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Aliqua non ex ut id occaecat eu mollit esse anim ea excepteur ullamco esse consectetur occaecat. Laboris in in sint nisi ut in dolor ut enim minim cupidatat quis culpa excepteur nulla. Sint elit commodo labore velit commodo dolore anim lorem ut ex veniam dolor. Incididunt aliquip duis esse nisi sunt tempor do enim in nulla tempor deserunt sint tempor adipiscing cillum irure sunt minim .'
]

{ #category : #'write barrier' }
GtCrasherGeneratedAKA >> ygfypuneknsvzvZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt."
	^ #jdjiqxlvgiulbggtcicdljdbdmmjtbub
]
