Class {
	#name : #GtCrasherGeneratedAFW,
	#superclass : #Object,
	#instVars : [
		'ktpehyjzglvdhik',
		'bakdqejdetmi',
		'abnpgg',
		'onkepbalkcbokq',
		'qqpxodxcnurlgfr',
		'dkzazggoslj'
	],
	#category : #'GToolkit-CrasherGenerated'
}

{ #category : #MonticelloGUI }
GtCrasherGeneratedAFW >> alvoplqrqifqBK [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ei."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Esse occaecat cillum anim nulla voluptate voluptate aliqua culpa ea consequat. Minim ut labore ea exercitation eiusmod esse in nulla culpa irure anim anim irure laboris deserunt excepteur dolore nulla. Amet est occaecat laboris non magna fugiat. Sint tempor ad pariatur dolore ipsum culpa et proident ut. Duis sint qui fugiat culpa ut magna incididunt veniam officia aute eiusmod cupidatat id aute in cillum fugiat consectetur anim. Cupidatat in laborum commodo sunt pariatur. Quis aute dolor sit dolor culpa exercitatio.'
]

{ #category : #enumeration }
GtCrasherGeneratedAFW >> alvoplqrqifqEY [
	^ #ibvhzukuhtzktqpebzfkogehhyhljtezixxeuqyiebwji
]

{ #category : #'brick-structure-events' }
GtCrasherGeneratedAFW >> alvoplqrqifqO [
	^ onkepbalkcbokq
]

{ #category : #'source pointers' }
GtCrasherGeneratedAFW >> bcjxbpAI [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ."
	^ #gvtfxmhyhsfxhhwvanqtkwqwlxpcjqbtncnvhpohh
]

{ #category : #'accessing scrollbars' }
GtCrasherGeneratedAFW >> bcjxbpAL [
	"Lorem ipsum dolor sit am."
	^ #iliouwzycfw
]

{ #category : #'tests - before' }
GtCrasherGeneratedAFW >> bcjxbpAT [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veni."
	^ #pgrrwdjkrycwkjljwiyfevyyrpialmmryjbktfkbgcwn
]

{ #category : #'scroll timing' }
GtCrasherGeneratedAFW >> bcjxbpBA [
	^ bakdqejdetmi
]

{ #category : #tag1 }
GtCrasherGeneratedAFW >> bcjxbpBZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo."
	^ #qrxmgpaaryyokgsqnw
]

{ #category : #refactoring }
GtCrasherGeneratedAFW >> bcjxbpDF [
	^ #[50 109 55 87 102 74 220 19 158 57 71 4 241 90 235 234 29 15 60 239 47 8 25 54 27 93 2 251 36 101 5 202 115 251 186 153 195 65 254 143 212 194 171 90 122 106 166 157 170 185 110 242 141 35 128 204 146 152 5 25 66 56 212 47 20 213 204 43 209 105 198 209 41 156 109 94 184 188 218 111 47 209 232 149 97 144 87 112 251 6 160 223 117 16 231 24 87 138 113 218 29 119 179 236 193 251 235 189 174 212 198 27 142 247 139 7 179 141 59 51 178 213 112 16 21 184 219 130 50 63 151 133 49 204 226 20 63 155 80 47 251 221 44 136 151 222 143 91 54 63 112 197 143 89 182 123 79 226 169 67 102 18 157 186 52 141 62 199 206 180 19]
]

{ #category : #'helpers-names' }
GtCrasherGeneratedAFW >> budbilseeqjCX [
	^ ktpehyjzglvdhik
]

{ #category : #'large integer arithmetic' }
GtCrasherGeneratedAFW >> budbilseeqjDR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n."
	^ #[15 159 63 226 40 237 160 40 117 3 197 48 168 148 149 229 221 75 180 99 36 39 154 208 163 22 73 202 171 36 54 2 229 125 205 35 177 235 30 255 96 48 215 178 244 199 54 219 34 218 134 92 94 175 16 50 187]
]

{ #category : #delivery }
GtCrasherGeneratedAFW >> budbilseeqjFK [
	^ #bntdmpfjbpdzl
]

{ #category : #'tests - allnodes' }
GtCrasherGeneratedAFW >> clmluusopxdkiCP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim venia."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure .'
]

{ #category : #'button-brick-creation' }
GtCrasherGeneratedAFW >> clmluusopxdkiED [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. U."
	^ qqpxodxcnurlgfr
]

{ #category : #'tests-floating' }
GtCrasherGeneratedAFW >> clmluusopxdkiES [
	"Lorem ipsum dolor sit amet, consectetur adipis."
	^ ktpehyjzglvdhik
]

{ #category : #selecting }
GtCrasherGeneratedAFW >> clmluusopxdkiFZ [
	^ dkzazggoslj
]

{ #category : #'file list menu' }
GtCrasherGeneratedAFW >> eqtaviuogtEE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut eni."
	^ #[126 10 184 10 184 71 136 31 18 195 128 252 30 9 210 227 146 159 106 16 85 92 31 175 39 53 229 163 112 68 215 26 175 138 199 60 158 106 70 123 88 221 21 236 187 102 53 240 216 24 48 110 144 236 31 99 143 218 124 240 66 7 118 57 194 242 149 78 13 90 176 210 98 241 204 55 140 28 165 28 95 95 56 181 130 232 221 124 123 9 222 36 37 11 208 110 110 15 111 72 39 64 148 85 254 220 25 17 249 113 229 209 136 96 175 96 224 141 55 246 17 244 93 53 166 127 197 54 143 175 76 219 4 208 251 202 200 219 48 64 70 5 175 13 242 47 98 202 81 133 53 130 179 121 75 64 27 82 11 234 50 231 178 96 198 134 164 17 140 237 217 225 251 16 7 33 143 102 99 107 3 160 168 72 13 167 86 223 15]
]

{ #category : #'testing-pragma' }
GtCrasherGeneratedAFW >> eqtaviuogtGJ [
	^ #[107 127 225 49 103 71 255 104 32 40 160 240 104 185 209 101 90 47 5 10 100 76 174 55 161 4 250 213 84 128 41 219 216 68 14 219 102 26 241 219 100 38 48 203 220 226 245 236 8 68 40 232 206]
]

{ #category : #'non-interactive' }
GtCrasherGeneratedAFW >> gpimjabqlmAA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun."
	^ #higetzuxw
]

{ #category : #'subclass creation - deprecated' }
GtCrasherGeneratedAFW >> gpimjabqlmAO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing."
	^ onkepbalkcbokq
]

{ #category : #'tests - optimized blocks' }
GtCrasherGeneratedAFW >> gpimjabqlmM [
	^ onkepbalkcbokq
]

{ #category : #'menu spec' }
GtCrasherGeneratedAFW >> gsonvcbhllxmCG [
	^ dkzazggoslj
]

{ #category : #'accessing - text' }
GtCrasherGeneratedAFW >> gsonvcbhllxmEF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud e."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, .'
]

{ #category : #'category - deprecated' }
GtCrasherGeneratedAFW >> gsonvcbhllxmFM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco la."
	^ #[36 122 73 118 211 176 236 67 255 124 35 112 169 206 248 136 51 191 108 70 62 68 182 49 185 253 246 201 154 190 252 55 25 3 119 72 105 189 219 24 249 186 124 171 7 192 178 252 42 6 62 52 182 246 3 238 226 40 175 184 27 170 20 101 37 120 35 197 17 12 78 52 41 242 29 165 92 248 218 78 53 164 5 7 165 38 161 8 30 42 136 162 82 48 193 4 223 210 252 38 81 191 122 149 38 12 190 27 182 23 20 67 200 24 145 238 218 26 114 121 41 93 185 237 180 16 75 60 82 104 195 66 5 216 197 253 117 194 21 182 40 167 100 143 62 66 205 196 75 144 157 171 96 16 245 51 131 227 97 56 87 59 164 183 165 57 89 115 11 255 169 93 60 63 230 2 86 220 8 9 210 197 25 99 69 121 30 180 82 238 204 196 72 21 39 190]
]

{ #category : #'api-window' }
GtCrasherGeneratedAFW >> gsonvcbhllxmFS [
	^ onkepbalkcbokq
]

{ #category : #visibility }
GtCrasherGeneratedAFW >> gyzwpyycyBE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu."
	^ abnpgg
]

{ #category : #'focus handling' }
GtCrasherGeneratedAFW >> gyzwpyycyBP [
	^ #xhrkdufehbhk
]

{ #category : #'test unique identifier' }
GtCrasherGeneratedAFW >> gyzwpyycyCL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu."
	^ #[32 35 161 137 44 119 12 3 48 156 47 218 84 20 215 52 61 132 9 125 215 79 40 186 181 52 227 8 165 79 24 159 148 144 134 69 172 191 9 52 29 89 201 25 140 123 103 207 64 166 233 224 138 124 206 49 200 224 2 251 234 251 220 28 171 232 72 157 77 71 141 160 77 220 48 249 117 32 183 163 69 168 171 72 229 243 167 9 139 228 151 113 193 35 87 140 155 210 186 207 169 240 44 71 152 58 221 144 248 36 150 35 35 174 234 45 210 180 215 192 119 15 16 121 102 142 100 208 53 247 235 92 3 125 241 84 16 117 38 155 55 57 134 9 149 75 195 83 112 155 1 165 53 13 168 96 143 224 105 2 73 5 1 121 135 148 116 131 118 45 200 14 23 120 59 1 166]
]

{ #category : #'tests - class variables' }
GtCrasherGeneratedAFW >> gyzwpyycyFV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e."
	^ #[234 230 49 42 148 78 25 176 234 40 86 85 66 155 138 56 212 254 22 239 115 23 235 79 251 90 183 145 107 23 227 165 150 204 145 78 209 41 5 166 114 111 67 63 249 250 123 217 251 74 154]
]

{ #category : #announcement }
GtCrasherGeneratedAFW >> gyzwpyycyQ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, s."
	^ #[59 232 214 42 149 187 126 192 24 214 112 130 78 236 204 233 212 171 87 11 20 202 80 119 252 123 146 144 225 88 32 134 193 173 157 196 79 205 139]
]

{ #category : #'visiting - three fingers gestures' }
GtCrasherGeneratedAFW >> gzdillrdvwfqmjfDZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ."
	^ #mrnxcuytqcuyolshpbclxtnswoltrlggfslrjvqhfngzmr
]

{ #category : #'accessing - computed' }
GtCrasherGeneratedAFW >> gzdillrdvwfqmjfGF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n."
	^ #[186 226 209 113 125 166 85 182 111 177 50 243 217 222 8 93 74 22 228 213 132 111 164 132 19 54 54 252 12 117 116 188 232 128 120 69 141 81 115 64 158 61 248 76 71 96 225 179 106 157 123 185 69 243 235 237 32 10 140 198 221 94 85 187 168 252 153 48 158 96 38 61 58 99 54 48 26 7 125 206 109 142 46 203 129 179 21 77 233 63 9 219 56 88 75 129 188 64 189 9 19 72 181 106 224 37 108 143 104 207 197 232 154 12 50 144 22 117 189 5 176 127 181 252 229 65 103 40 243 145 224 154 185 69 63 210 182 16 93 165 175 122 11 205 35 246 215 132 222 177 12 136 20 211 205 27 220 204 164 90 173 21 227 114 37 147 45 232 177 171 127 47 203 43 37 119 131 48 54 138 128 192 46 117 137 179 4 72 127 204 254 72]
]

{ #category : #'tests - yyyy pattern' }
GtCrasherGeneratedAFW >> hsmyqaaofsAJ [
	"Lorem ipsum dolor s."
	^ #[235 121 49 191 169 17 174 192 42 121 134 15 137 69 243 211 141 152 198 33 20 192 98 128 84 145 206 222 2 253 198 182 159 114 47 161 222 215 137 164 86 82 76 168 140 252 24 44 173 59 180 39 119 148 197 208 220 210 7 1 241 1 193 157 83 66 198 222 117 64 160 152 182 138 123 51 250 75 248 250 188 221 109]
]

{ #category : #'expanding-collapsing' }
GtCrasherGeneratedAFW >> hsmyqaaofsEL [
	^ #tucebxzpptnyamltamtv
]

{ #category : #'card in a stack' }
GtCrasherGeneratedAFW >> hsmyqaaofsGI [
	^ #eafepgimtwomaovojteoi
]

{ #category : #'private - 3 installing' }
GtCrasherGeneratedAFW >> hsmyqaaofsV [
	^ #udiogltnqjhqyygpbyknxldbanwn
]

{ #category : #ConfigurationOfSymbolic }
GtCrasherGeneratedAFW >> ilofzaadAH [
	^ onkepbalkcbokq
]

{ #category : #recategorized }
GtCrasherGeneratedAFW >> ilofzaadB [
	^ #[63 4 62 64 125 181 233 136 96 222 67 9 162 177 169 124 45 38 20 95 249 110 247 150 238 74 152 35 139 57 153 246 55 172 122 132 218 121 147 228 150 4 144 71 158 119 207 216 55 179 35 164 216 130 100 130 57 196 215 25 235 195 194 18 69 26 7 138 180 152 101 193 252 51 4 166 18 24 70 49 149 35 72 26 237 85 126 99 31 200 41 112 251 5 13 187 242 180 123 175 247 147 151 84 68 24 195 47 195 145 15 209 105 7 137 209 221 4 137 185 81 215 106 33 164 113 97 2 41 53 45 70 247 235 132 198 180 83 228 81 248 197 145 125 14 193 122 48 145 23 168 245 247 150 173 5 139 227 240 97 86 125 183 117]
]

{ #category : #'private - access' }
GtCrasherGeneratedAFW >> ilofzaadBM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco la."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Qui cillum ullamco do ex dolor dolore esse in in esse anim sit anim. Incididunt nostrud velit consequat dolor ea aute reprehenderit in sit esse aliqua est sed. Nulla in elit anim adipiscing ipsum ipsum aliquip proident in tempor dolore laboris adipiscing ex sed incididunt. Fugiat occaecat et reprehenderit.'
]

{ #category : #scoping }
GtCrasherGeneratedAFW >> ilofzaadCQ [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Exc.'
]

{ #category : #infos }
GtCrasherGeneratedAFW >> imsapnbkkhjokcFA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim venia."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Nulla magna irure aute. In tempor nulla ad labore. Nulla ut aute. Voluptate commodo veniam consectetur sint deserunt exercitation non amet culpa incididunt sunt consequat occaecat duis sunt tempor. Sint voluptate adipiscing elit quis eu excepteur. Elit ex esse minim cupidatat voluptate mollit qui ipsum voluptate est ut commodo pariatur ullamco veniam cillum tempor. Sed enim reprehenderit incididunt ex enim commodo sunt incididunt ullamco non eiusmod nisi proident mollit. Commodo aliquip fugiat tempor lorem. Pariatur cup.'
]

{ #category : #'primitives-incremental' }
GtCrasherGeneratedAFW >> imsapnbkkhjokcGE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol."
	^ bakdqejdetmi
]

{ #category : #'mouse capture' }
GtCrasherGeneratedAFW >> imsapnbkkhjokcX [
	^ #[90 108 49 204 125 30 153 12 163 186 124 63 231 27 253 174 204 182 38 80 149 213 141 74 12 68 247 69 92 60 38 172 250 79 112 49 151 194 170 144 157 9 64 231 179 138 73 17 182 31 18 61 62 121 161 104 239 179 118 81 248 120 235 172 184 21 153 87 133 91 52 6 233 197 220 130 169 210 255 247 63 126 247 185 105 96 12 65 247 208 220 179 251 149 146 160 249 184 237 54 172 19 45 13 45 237 128 137 224 48 38 34 55 103 181 222 214 100 45 183 4 32 12 81 216 89 209 139 7 198 177 175 152 77 176 4 141 245 25 95 143 58 128 213 191 128 74 60 142 35 13 34 20 250 186 145 156 175]
]

{ #category : #'file open/close' }
GtCrasherGeneratedAFW >> jzzugerfskbhmDO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et ."
	^ #aktdmbkwwrcqromvfapbpnhfofrezade
]

{ #category : #masking }
GtCrasherGeneratedAFW >> jzzugerfskbhmFN [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e."
	^ #[166 58 136 228 130 162 75 113 62 236 135 83 121 224 151 252 71 63 146 251 135 160 152 168 227 135 138 73 186 141 219 214 12 114 162 13 64 59 158 151 62 69 167 36 214 11 255 151 210 161 40 144 47 122 3 62 61 114 108 24 32 225 112 122 235 141 17 145 99 178 68 205 180 91 148 33]
]

{ #category : #'public declaration accessing' }
GtCrasherGeneratedAFW >> kbkghrdkgrnvtyC [
	"Lorem ipsum dolor sit amet, ."
	^ #[23 237 72 59 93 145 182 248 128 42 92 18 156 2 50 163 239 249 101 44 36 154 247 82 194 126 19 128 127 211 220 88 181 130 19 12 151 184 50 26 154 218 248 3 51 46 160 195 145 116 225 112 133 134 104 70 91 216 242 251 52 136 8 237 62 215 250 176 160 225 32 79 215 57 109 153 25 104 231 10 74 14 206 185 4 199 105 167 23 163 80 144 85 246 184 145 112 171 87 107 82 102 109 139 177 198 152 147 10 99 204 165 6 199 157 171 116 137 17 29 58 219 39 18 59 162 126 208 219 169 39 226 39 121 46 224 238 140 199 166 185]
]

{ #category : #descriptions }
GtCrasherGeneratedAFW >> kbkghrdkgrnvtyE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, q."
	^ #[4 189 59 179 43 210 66 229 100 228 133 253 32 117 156 95 108 118 140 77 198 108 177 202 198 49 99 22 123 118 102 190 228 35 41 217 169 91 217 247 111 42 133 210 148 70 8 182 28 111 155 44 230 205 141 5 159 119 176 110 38 194 80 142 170 205 88 27 239 232 244 231 107 156 8 116 199 98 73 32 86 179 24 62 231 133 119 64 152 18 3 108 127 163 223 15 12 176 167 3 85 204 246 12 217 151 163 169 26 128 157 242 216 123 190 175 193 15 8 9 20 74 255 196 59 94 77 214]
]

{ #category : #'api-events-compatibility' }
GtCrasherGeneratedAFW >> kbkghrdkgrnvtyEV [
	^ onkepbalkcbokq
]

{ #category : #'see class side' }
GtCrasherGeneratedAFW >> kbkghrdkgrnvtyFP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ven."
	^ #vdnokjyrokcjxumnhotafjclfgccicrwyipqubqytlgix
]

{ #category : #'tests - relation order' }
GtCrasherGeneratedAFW >> khsiwbubmxflrhjDB [
	^ #[123 190 64 223 63 174 8 102 94 58 33 82 156 216 152 87 118 221 36 247 116 20 141 36 125 38 49 191 44 206 26 33 232 112 242 132 122 176 160 166 219 156 147 109 232 160 180 38 89 230 48 145 155 15 190 129 179 186 109 221 200 183 243 75 221 97 145 9 232 220 14 239 187 100 44 86 226 61 133 92 37 144 35 64 15 209 93 238 146 99 58 102 48 189 83 148 67 238 128 247 157 122 150 169 212 122 86 209 126 152 127 52 25 121 123 70 253 166 107 220 208 186 165 6 150 202 2 91 128 230 183 206 201 62 56 85 40 209 173 152 189 249 204 185 125 58 108 87 241 179 179 186 254 214 28 227 63 218 218 242 193 11 196 103 60 81 209 138 186 186 100 213 202]
]

{ #category : #'scope creation' }
GtCrasherGeneratedAFW >> khsiwbubmxflrhjDC [
	^ onkepbalkcbokq
]

{ #category : #'backward compatibility' }
GtCrasherGeneratedAFW >> khsiwbubmxflrhjFY [
	^ #rnriuzwialcozitpfdgcctogljogxtivlqahqioatpfxk
]

{ #category : #removing }
GtCrasherGeneratedAFW >> kmzeejxqornBL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ali."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Officia aliqua adipiscing dolor consectetur deserunt aliqua eiusmod lorem magna. In consectetur sunt pariatur. Dolor voluptate sed labore minim deserunt do ad eiusmod irure enim et mollit in minim elit in commodo exercitation. Anim occaecat fugiat esse occaecat consequat ut culpa quis irure. Reprehenderit reprehenderit ipsum mollit pariatur veniam. Enim anim cupidatat ex reprehenderit sint sed sunt ea nisi mollit in incididunt dolore cillum culpa deserunt minim ex sit sunt. Labore sint .'
]

{ #category : #'epicea support' }
GtCrasherGeneratedAFW >> kmzeejxqornDA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis."
	^ #[9 113 191 129 26 92 249 155 34 130 75 198 96 162 105 207 28 145 179 228 13 41 39 176 100 183 233 242 135 50]
]

{ #category : #'keymap building' }
GtCrasherGeneratedAFW >> kmzeejxqornGC [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehen.'
]

{ #category : #scoping }
GtCrasherGeneratedAFW >> kmzeejxqornS [
	^ #[4 134 19 33 39 170 197 107 206 180 94 195 65 72 218 66 103 95 28 120 96 80 137 48 131 233 220 162 164 205 182]
]

{ #category : #morphing }
GtCrasherGeneratedAFW >> ktcmhaauvylBF [
	"Lorem ipsum dolor sit amet, consectet."
	^ #jpwmqhyowdscdjtesusiaqyccvvsaxspvfurfccsuio
]

{ #category : #'border-styles-buttons' }
GtCrasherGeneratedAFW >> ktcmhaauvylCM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud e."
	^ dkzazggoslj
]

{ #category : #'brick-rubric' }
GtCrasherGeneratedAFW >> ktcmhaauvylDI [
	^ dkzazggoslj
]

{ #category : #'tests-numbers' }
GtCrasherGeneratedAFW >> ktcmhaauvylDK [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmo."
	^ #eklmignvjetjwohabhxinbcpqmzkmoykxjnrprgeyqjqshzqp
]

{ #category : #'link api' }
GtCrasherGeneratedAFW >> ktcmhaauvylFX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et ."
	^ bakdqejdetmi
]

{ #category : #geometry }
GtCrasherGeneratedAFW >> ktcmhaauvylH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Dolore non adipiscing laboris aliquip velit labore fugiat fugiat reprehenderit tempor laborum dolor in cillum non id anim irure excepteur magna. Ad sit aliquip labore enim mollit cupidatat sunt mollit in enim sit non ea veniam cupidatat lorem reprehenderit pariatur velit elit. Consequ.'
]

{ #category : #'critic creation' }
GtCrasherGeneratedAFW >> lvyijbhagtnhxAE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm."
	^ #[182 104 120 48 114 134 208 202 33 179 3 228 204 192 70 124 204 71 67 73 11 198 255 198 211 4 114 47 232 139 207 210 159 59 207 29 224 8 193 78 42 198 42 147 43 241 204 238 184 229 16 215 197 230 224 229 54 236 200 6 189 5 223 218 254 176 242 209 172 144 235 70 121 38 219 189 136 221 154 118 138 86 132 124 188 218 113 230 149 116 60 74 121 3 59 210 105 234 109 230 130 49 57 205 31 21 91 117 199 17 215 116 246 35 4 58 214 129 231 119 233 114 39 158 103 17 201 44 244 88 183 72 60 246 97 39]
]

{ #category : #'tests - dictionary key access' }
GtCrasherGeneratedAFW >> lvyijbhagtnhxEH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing ."
	^ qqpxodxcnurlgfr
]

{ #category : #'morphic ui' }
GtCrasherGeneratedAFW >> lvyijbhagtnhxEQ [
	"Lorem ipsum dolor sit amet, consectetur adipisc."
	^ #msswclphqilxbgqhwpmryjdzmbb
]

{ #category : #'tests - internet' }
GtCrasherGeneratedAFW >> lvyijbhagtnhxER [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio."
	^ #[20 93 155 178 226 98 167 45 234 130 220 71 81 186 58 116 217 171 215 171 255 19 118 220 89 140 72 209 74 157 127 63 3 113 166 179 46 216 2 184 135 22 9 112 240 110 102 155 202 140 142 90 233 135 60 190 21 217 28 220 179 85 119 60 90 74 216 83 236 91]
]

{ #category : #preamble }
GtCrasherGeneratedAFW >> lvyijbhagtnhxK [
	"Lorem ipsum dolor sit amet, consectetur adipiscing eli."
	^ #[106 250 82 166 76 22 85 233 107 220 7 109 146 47 7 54 104 172 118 130 29 231 33 27 134 44 242 92 75 167 29 4 210 21 65 108 76 204 97 161 18 122 169 38 96 64 210 47 83 118 82 5 21 225 206 37 164 113 2 223 123 138 5 214 143 166 159 217 167 202 32 209 140 67 17 111 195 223 17 170 56 213 133 170 20 36 30 126 156 41 239 178 15 70 34 75 49 128 79 246 180 234 38 133 195 17 205 236 17 70 179 176 134 1 125 171 199 122 214 76 62 229 79 79 4 69 247 227 224 224 212 224 83 176 181 187 147 151 39 105 127 30 77 234 116 62 63 17 68 104 137 188 73 189 70 133 12 122 121 142 165]
]

{ #category : #'source navigation' }
GtCrasherGeneratedAFW >> lzivergntbeoAG [
	^ #[208 77 34 38 2 28 217 187 186 35 225 51 82 31 191 151 144 21 1 142 143 103 94 46 129 172 44 73 62 28 12 172 204 4 155 195 57 241 214 176 71 186 170 67 100 1 233 106 6 241 92 15 35 73 207 212 229 157 19 217 165 12 161 54 35 11 248 123 22 10 232 97 141 236 133 203 44 144 199 135 101 232 43 51 117 40 232 243 131 23 110 119 188 106 74 227 18 117 15 231 139 108 90 136]
]

{ #category : #'refactory-changes' }
GtCrasherGeneratedAFW >> lzivergntbeoFL [
	"Lorem ipsum dolor sit amet, consectetur ."
	^ #[34 16 61 131 12 122 175 79 156 189 203 71 53 184 201 99 62 217 6 115 5 127 41 163 220 154 207 49 82 227 12 42 198 195 5 111 253 235 233 104 12 193 219 223 232 118 153 149 220 122 92 45 48 37 158 184 209 248 47 12 198 88 102 205 168 50 56 144 176 248 3 198 52 172 168 195 86 130 165 249 89 235 12 146 105 253 43 195 164 151 96 151 71 245 247 208 199 115 49 176 83 74 230 106 247 240 22 181 65 251 4 53 50 14 128 60 204 123 55 246 35 37 30 197 36 150 68 63 242 66 206 117 233 30 192 46 155 210 87 48 78 218 21 91 240 111 88 99 74 157 139 164 229 71 198 99 84 162 39 204 245 223 223 220 138 31 93 85 151 223 20 51 196 31 22 152 79 43 90 154 135 81 237 79]
]

{ #category : #'tests-blocks' }
GtCrasherGeneratedAFW >> lzivergntbeoT [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Ea veniam magna sed enim nostrud. Laboris magna aliquip irure qui nisi consequat voluptate irure esse exercitation consequat ad amet culpa officia id sed quis pariatur proident. Sed consequat proident tempor veniam ut mollit commodo minim irure cupid.'
]

{ #category : #width }
GtCrasherGeneratedAFW >> mzybwdFF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sit eu amet quis culpa proident tempor id laborum et elit consequat amet laboris sint lorem culpa. Mollit in consectetur dolor magna dolore excepteur anim non irure commodo consectetur co.'
]

{ #category : #'label-brick-accessing' }
GtCrasherGeneratedAFW >> mzybwdGA [
	^ #bhvwistjtocwdfxaerwkbfgkwusbwqv
]

{ #category : #'reflective operations' }
GtCrasherGeneratedAFW >> mzybwdZ [
	^ #vsubokdrpqlcpkblxnpxyqzikcjzyullllbrfxdeutq
]

{ #category : #'submorphs-accessing' }
GtCrasherGeneratedAFW >> nrokscidisqkDD [
	^ ktpehyjzglvdhik
]

{ #category : #'performing-changes' }
GtCrasherGeneratedAFW >> nrokscidisqkDV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea c.'
]

{ #category : #'class management' }
GtCrasherGeneratedAFW >> nrokscidisqkGB [
	^ #hfweoliihioeqyjakwmvjfzvkdseouhhmxcuqhvisymtjcyveromfzf
]

{ #category : #sounds }
GtCrasherGeneratedAFW >> nrokscidisqkGL [
	^ #rmhyapwngtfqdpypxdipjhmpspesledffytbjqfwss
]

{ #category : #tarjan }
GtCrasherGeneratedAFW >> nyulznzxyAX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,."
	^ ktpehyjzglvdhik
]

{ #category : #'drag and drop' }
GtCrasherGeneratedAFW >> nyulznzxyFD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit."
	^ #[59 232 214 42 149 187 126 192 24 214 112 130 78 236 204 233 212 171 87 11 20 202 80 119 252 123 146 144 225 88 32 134 193 173 157 196 79 205 139]
]

{ #category : #'non-accessing' }
GtCrasherGeneratedAFW >> nyulznzxyW [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol.'
]

{ #category : #test }
GtCrasherGeneratedAFW >> ohehituoodAK [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ."
	^ bakdqejdetmi
]

{ #category : #'converting-arrays' }
GtCrasherGeneratedAFW >> ohehituoodET [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et do."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehend.'
]

{ #category : #'accessing - projects' }
GtCrasherGeneratedAFW >> ohehituoodEW [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor."
	^ #[50 3 75 136 148 184 221 125 163 252 72 87 19 95 160 132 211 244 118 195 235 143 128 72 110 199 101 108 221 62 11 151 171 19 168 69 16 246 100 91 212 48 127 244 170 71 148 29 3 73 8 85 122 191 189 103 147 153 15 124 112 18 86 224 170 165 36 164 103 43 249 222 121 71 194 233 107 26 62 211 171 24 79 68 64 107 210 166 170 135 73 62 163 239 47 122 126 74 64 72 203 194 184 13 167 142 152 181 152 175 90 67 127 208 101 94 167 101 134 243 16 43 86 234 198 107 122 220 191 106 239 94 78 248 126 151 41 58 231 113 138 64 174 90 198 25 9 72 214 57 9 199 209 29 163 102 54 107 241 92 120 67 82 154 158 200 240 177 95 17 49 30 85 104 51 188 56 158 244 30]
]

{ #category : #'public editing' }
GtCrasherGeneratedAFW >> ohehituoodFI [
	^ #[26 194 250 174 14 187 216 9 90 90 40 60 49 220 55 197 249 248 134 62 239 225 29 4 63 77 82 201 90 114 111 170 85 78 176 153 165 147 87 160 240 75 250 37 190 111 73 214 75 216 79 19 108 7 232 183 48]
]

{ #category : #'scroll cache' }
GtCrasherGeneratedAFW >> ohehituoodI [
	"Lorem ipsum dolor sit amet, consectetur adipisc."
	^ #[35 201 7 66 213 59 162 84 187 44 21 188 239 111 180 159 96 16 202 213 207 16 228 48 102 78 173 56 111 3 183 38 247]
]

{ #category : #install }
GtCrasherGeneratedAFW >> ohehituoodP [
	"Lorem ipsum dolor sit amet, con."
	^ #[194 81 132 231 166 195 32 225 92 187 46 195 132 135 210 133 247 172 93 202 246 112 43 230 43 127 146 10 119 208 249 246 186 149 49 188 233 6 29 110 154 220 148 137 135 14 70]
]

{ #category : #'jensen device examples' }
GtCrasherGeneratedAFW >> oioubjDY [
	^ bakdqejdetmi
]

{ #category : #'accessing selection' }
GtCrasherGeneratedAFW >> oioubjEZ [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Ut minim dolore exercitation exercitation nisi consequat labore et ullamco voluptate dolore quis ullamco dolore magna qui. Ea ut in magna .'
]

{ #category : #running }
GtCrasherGeneratedAFW >> oioubjFQ [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Eu minim non commodo exercitation lorem anim esse irure duis ut laborum ea in sint exercitation quis in aliquip. Magna ut. In sed excepteur velit in occaecat labore sit nisi sint. Ullamco excepteur magna cupidatat anim fugiat anim labore cillum anim veniam velit magna culpa veniam ea. Sit do voluptate exercitation cupidatat anim amet id quis laboris eiusmod. Sit cillum aute veniam qui a.'
]

{ #category : #query }
GtCrasherGeneratedAFW >> onyxtiBS [
	^ #abirbnqvqvaxzihg
]

{ #category : #'tests - endswith' }
GtCrasherGeneratedAFW >> onyxtiEO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut en."
	^ ktpehyjzglvdhik
]

{ #category : #auxiliar }
GtCrasherGeneratedAFW >> onyxtiFO [
	^ #xsjkurqcudywofmnqsybffeitojdwbkdgfovnakegikwezmetecj
]

{ #category : #'initailize-release' }
GtCrasherGeneratedAFW >> onyxtiU [
	^ #[240 50 14 65 160 225 127 57 255 209 34 206 93 132 74 90 134 98 173 149 154 3 136 165 24 5 184 112 225 220 60 218 23 211 95 118 204 52 198 168 13 162 158 72 99 179 163 177 32 237 61 118 66 91 167 49 71 90 99 160 29 238 145 138 50 209 6 231 226 76 107 25 129 50 132 210 62 84 37 181 31 75 106 98 201 22 37 55 190 117 27 22 145 119 191 128 73 229 230 157 241 5 226 157 182 137 71 163 145 61 47 241 63 228 87 223 182 207 29 58 4 241 157 220 73 230 46 46 178 105 87 85 122 182 85 233 40 245 89 10 164 33 209 83 161 196 106 138 91 1 73 122 107 232 26 92 120 108 254 168 191 64 224 165 242 86 63 163 71 171 39 184 153 185 95 70 101 205 194 182 57 54 84 232 52 226 148]
]

{ #category : #metaclass }
GtCrasherGeneratedAFW >> plzdnbqtdjiehAD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ."
	^ #cjklebxjhixxmtbztndvzz
]

{ #category : #'tests parsing faulty' }
GtCrasherGeneratedAFW >> plzdnbqtdjiehBT [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolor."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Veniam ad elit ni.'
]

{ #category : #model }
GtCrasherGeneratedAFW >> plzdnbqtdjiehCA [
	^ #ufbqjsqxkwhaqauvkotzmwcjeufmfjcexxphmdsryjkzqbahvluh
]

{ #category : #remnant }
GtCrasherGeneratedAFW >> plzdnbqtdjiehCW [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Pariatur dolore sit velit reprehenderit magna laborum excepteur qui. Fugiat ea commodo labore nulla ut excepteur nisi fugiat culpa dolore cupidatat id cupidatat dolor laborum cillum fugiat. Ipsum elit do voluptate sint elit sunt. Consectetur fugiat. 

Amet sed duis in pariatur c.'
]

{ #category : #'completion engine' }
GtCrasherGeneratedAFW >> plzdnbqtdjiehDG [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut ."
	^ #[12 33 122 132 46 159 19 237 244 220 21 39 90 42 54 219 28 74 144 226 130 50 58 189 208 71 61 254 244 114 143 39 195 43 147 213 144 252 151 32 237 108 30 188 21 97 48 57 47 155 150 83 84 173 29 188]
]

{ #category : #'accessing - subwidgets' }
GtCrasherGeneratedAFW >> plzdnbqtdjiehEN [
	^ onkepbalkcbokq
]

{ #category : #'parsing-internal' }
GtCrasherGeneratedAFW >> plzdnbqtdjiehY [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex."
	^ ktpehyjzglvdhik
]

{ #category : #'API-tags' }
GtCrasherGeneratedAFW >> pooignigiqzwfAS [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sint pariatur mollit eu eiusmod mollit. 

Ea laboris voluptate non nisi magna et proident amet id dolore dolore in sint. Esse cupidatat ut veniam proident laborum anim elit in ullamco irure eu adipiscing sit ea voluptate esse. Laboris mollit. Do esse ut deserunt. Anim proident nisi dolor incidi.'
]

{ #category : #slot }
GtCrasherGeneratedAFW >> pooignigiqzwfBB [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et .'
]

{ #category : #'label-brick-testing' }
GtCrasherGeneratedAFW >> pooignigiqzwfFB [
	^ onkepbalkcbokq
]

{ #category : #scopes }
GtCrasherGeneratedAFW >> pxvkdsgzpudzyBU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt."
	^ dkzazggoslj
]

{ #category : #'huffman trees' }
GtCrasherGeneratedAFW >> pxvkdsgzpudzyCJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ma."
	^ #[1 4 141 147 106 25 10 64 33 201 45 179 22 52 13 240 96 251 173 195 101 204 190 217 203 27 34 177 4 231 207 148 175 10 197 140 55 210 230 221 48 220 68 252 181 205 75 42 251 135 86 233 128 244 74 197 28 58 88 77 232 149 76 84 180 211 11 41 227 205 140 23 4 156 19 6 239 183 68 196 15 9 229 67 185 97 105 217 157 38 162 189 73 140 229 167 130 27 89 59 233 193 187 39 136 125 121 179 26 29 11 113 71 140 165 121 240 185 58 176 87 119 185 123 209 209 8 17 115 6 48 56 8 23 9 230 203 105 82 149 53 105 21 160 30 176 196 156 56 80 77 2 213 149 236 148 30 235 54 148 158 233 64 247 107 246 41 82]
]

{ #category : #'file system' }
GtCrasherGeneratedAFW >> pxvkdsgzpudzyEI [
	"Lorem ipsum dolor s."
	^ #[235 121 49 191 169 17 174 192 42 121 134 15 137 69 243 211 141 152 198 33 20 192 98 128 84 145 206 222 2 253 198 182 159 114 47 161 222 215 137 164 86 82 76 168 140 252 24 44 173 59 180 39 119 148 197 208 220 210 7 1 241 1 193 157 83 66 198 222 117 64 160 152 182 138 123 51 250 75 248 250 188 221 109]
]

{ #category : #'event field' }
GtCrasherGeneratedAFW >> pxvkdsgzpudzyFE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing."
	^ #[225 247 98 105 120 198 2 139 124 252 15 142 126 170 129 139 68 117 36 92 28 119 31 143 37 209 78 181 120 126 202 154 183 30 21 1 51 66 135 115 44 247 207 15 178 170 136 49 48 39 36 107 16 203 40 20 14 110 190 182 59 75 183 87 88 246 201 34 113 33 99 48 109 146 185 45 86 155 131 120 79 188 196 167 67 78 187 133 25 22 19 153 210 21 180 101 132 116 167 215 64 110 72 163 169 61 236]
]

{ #category : #'handling transmission' }
GtCrasherGeneratedAFW >> pxvkdsgzpudzyGD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n."
	^ #[224 158 117 226 23 85 120 168 139 45 155 93 170 254 86 180 218 62 3 207 135 253 129 41 207 72 240 26 228 181 221 96 234 189 159 126 44 192 215 80 35 143 27 73 143 198 121 160 125 12 70 96 252 9 166 253 198 172 226 177 156 31 14 162 55 176 17 72 53 226 216 175 92 115 205 96 215 220 211 121 86 20 101 21 133 161 194 106 252 112 208 95 26 68 73 67 49 232 225 96 173 175 138 163 149 133 35 228 95 102 175 57 244 13 142 71 81 169 206 109 251 36 66 80 161 23 166 234 214 162 213 206 10 140 151 169 89 247 235 190 91 181 45 60 153 30 154 203 181 171 197]
]

{ #category : #'test - accessing source' }
GtCrasherGeneratedAFW >> qtguacrahsxBJ [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in cu.'
]

{ #category : #'tests - on-fork' }
GtCrasherGeneratedAFW >> qtguacrahsxCD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
	^ #[33 194 241 176 42 85 249 157 107 78 217 36 179 90 107 142 166 111 178 134]
]

{ #category : #'tests-cse' }
GtCrasherGeneratedAFW >> qtguacrahsxGG [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Veniam laboris sit in eu esse ut anim amet reprehenderit et ipsum nisi dolor velit velit sunt. Voluptate elit dolore nostrud sint magna. Quis in aliquip sint ea irure nulla ea cillum deserunt id consectetur ad ex voluptate. Sunt elit sed lorem aliqua sit consectetur do.'
]

{ #category : #'tests - conditions' }
GtCrasherGeneratedAFW >> qylerrxalqtvfqxCO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing e."
	^ bakdqejdetmi
]

{ #category : #'handling fingers' }
GtCrasherGeneratedAFW >> qylerrxalqtvfqxCV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

In dolor exercitation dolore incididunt exercitation veniam id aute in est excepteur quis. Culpa in et tempor eu mollit dolor ut esse occaecat cupidatat. Labore excepteur consectetur. Fugiat ex quis magna duis commodo cillum ea in sint proident sint aute dolore cillum mollit ex proident elit irure aliqua. Velit quis esse incididunt consequat incididunt deserunt. Consequat veniam in proident culpa veniam. Mollit excepteur qui nisi. Incididunt veniam dolor ad eu duis sit laboris et incididunt anim. Enim consectetur eiusmod veniam labor.'
]

{ #category : #invoking }
GtCrasherGeneratedAFW >> qylerrxalqtvfqxEJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun."
	^ #[228 49 149 254 58 19 91 173 191 22 242 254 92 210 195 126 64 59 78 10 168 240 119 171 13 64 167 193 161 82 207 8 226 195 239 104 146 70 141 53 209 107 43 142 97 101 14 119 196 19 202 113 108 7 4 56 95 58 31 81 98 170 21 164 1 40 2 110 30 173 189 111 95]
]

{ #category : #entries }
GtCrasherGeneratedAFW >> qylerrxalqtvfqxEK [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Elit aute fugiat voluptate ut laborum esse velit consequat minim eu fugiat officia incididunt incididunt sunt deserunt in sit dolore aliquip. Qui in nulla aute sunt consequat ullamco irure. Excepteur id mollit nostrud esse. Elit sit enim ipsum ut lorem ex proident eiusmod magna ut in lorem et. Amet in ad ex dolore est. Cillum voluptate ut velit elit laboris reprehenderit duis adipiscing proident officia aute eiusmod. Do velit ullamco do mollit irure .'
]

{ #category : #'mocking taskbar' }
GtCrasherGeneratedAFW >> qylerrxalqtvfqxFC [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqu."
	^ #[241 36 14 211 2 170 244 199 189 153 156 234 238 40 58 228 171 226 78 27 238 35 162 84 236 178 151 88 141 252 51 164 88 46 53 9 247 32 124 90 39 73 85 243 34 69 162 38 230 25 178 239 193 235 42 42 106 3 129 54 248 26 110 16 116 227 80 210 58 138 42 93 24 104 44 55 38 211 45 250 252 5 171 181 139 11 121 57 175 146 75 118 11 148 46 100 147 89 38 90 143 71 122 214 81 110 27 25 232 198 41 246 170 224 36 58 67 164 80 75 37 21 160 124 192 157 205 108 197 130 108 142 218 204 37 216 46 188 182 192]
]

{ #category : #'tests-select-index' }
GtCrasherGeneratedAFW >> rbswliBV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, se."
	^ #ussifmmqk
]

{ #category : #construction }
GtCrasherGeneratedAFW >> rkusjpwofubpvutAF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mi."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia des.'
]

{ #category : #'expected failures' }
GtCrasherGeneratedAFW >> rkusjpwofubpvutCC [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm."
	^ bakdqejdetmi
]

{ #category : #'tests version increment/decrement' }
GtCrasherGeneratedAFW >> rkusjpwofubpvutDE [
	^ dkzazggoslj
]

{ #category : #width }
GtCrasherGeneratedAFW >> rkusjpwofubpvutDN [
	^ #[144 30 64 37 173 165 136 36 37 177 48 13 235 196 131 21 37 78 40 191 132 22 64 162 71 142 105 163 46 216 193 230 229 169 24 219 56 224 245 128 7 194 101 143 53 151 105 220 161 109 129 238 237 98 149 113 242 193 206 163 160 167 244 22 155 61 194 195 127 9 37 202 61 191 192 78 249 212 51 87 115 179 66 39 128 221 153 254 231 21 146 29 1 242 107 87 159 116 80 15 182 8 230 150 234 97]
]

{ #category : #'api-valueHolder' }
GtCrasherGeneratedAFW >> rkusjpwofubpvutFR [
	^ #[7 1 181 48 74 207 175 156 21 5 164 183 108 107 176 143 168 114 32 111 45 156 52 130 195 59 1 172 178 245 66 163 144 65 147 146 227 141 190 228 156 198 112 206 1 155 210 183 78 163 222 110 237 191 22 145 237 83 249 77 41 91 33 152 177 158 32 147 51 30 144 89 237 38 73 134 6 79 124 116 187 134 159]
]

{ #category : #presentation }
GtCrasherGeneratedAFW >> smlawslmtbloBW [
	^ #rnulkrdlyonpseetu
]

{ #category : #privileged }
GtCrasherGeneratedAFW >> smlawslmtbloCS [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore."
	^ #hzkklwukedcoleekeimyvomndhmxyqtzmkzasggswv
]

{ #category : #'tests-shared pools' }
GtCrasherGeneratedAFW >> smlawslmtbloDH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmo."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi u.'
]

{ #category : #'tests - bits' }
GtCrasherGeneratedAFW >> smlawslmtbloEM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. U."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, su.'
]

{ #category : #'examples-blocks' }
GtCrasherGeneratedAFW >> smlawslmtbloEX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inci."
	^ #[202 78 21 120 183 27 255 235 241 188 103 245 211 38 68 175 184 240 33 90 183 19 11 105 217 175 155 212 206 28 82 234 162 177 80 7 2 219 223 62 209 206 15 48 239 72 151 13 138 41 57 245 161 192 167 10 15 199 221 192 139 203 79 180 36 198 197 131 41 99 177 48 116 247 156 176 207 81 183 70 164 240 117 22 19 60 170 66 111 106 206 226 97 220 106 234 12 119 115 11 79 98 107 230 105 163 155 26 142]
]

{ #category : #'method generation' }
GtCrasherGeneratedAFW >> smlawslmtbloFU [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offi.'
]

{ #category : #'acessing text' }
GtCrasherGeneratedAFW >> tbzwaijofoerAQ [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offici.'
]

{ #category : #'tests - operations on methods' }
GtCrasherGeneratedAFW >> tbzwaijofoerDL [
	"Lorem ipsum dolor sit amet, consectetur ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Id dolore. Commodo ad pariatur ut sed dolore dolor ut. Incididunt sint qui enim laborum quis nostrud adipiscing .'
]

{ #category : #intializing }
GtCrasherGeneratedAFW >> tlimhfvupwvBN [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepte.'
]

{ #category : #'extended bytecode generation' }
GtCrasherGeneratedAFW >> tlimhfvupwvBQ [
	^ qqpxodxcnurlgfr
]

{ #category : #packages }
GtCrasherGeneratedAFW >> tlimhfvupwvCI [
	^ #[224 200 254 112 93 209 79 52 40 202 101 186 38 74 214 180 34 50 240 49 246 146 19 73 243 89 125 22 50 76 85 25 14 64 142 64 192 235 133 159 95 229]
]

{ #category : #cycling }
GtCrasherGeneratedAFW >> tlimhfvupwvDW [
	"Lorem ipsum dolor sit amet, consectet."
	^ qqpxodxcnurlgfr
]

{ #category : #menu }
GtCrasherGeneratedAFW >> tlimhfvupwvEU [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ul.'
]

{ #category : #'popup - layout' }
GtCrasherGeneratedAFW >> tlimhfvupwvFT [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

In ea deserunt sed laborum. Sint ad elit ipsum consectetur in consequat. Nulla nulla in et elit irure veniam magna excepteur voluptate exercitation sed laboris elit labore in voluptate. Ea dolor irure reprehenderit commodo eiusmod consequat nulla ea quis sit et ut enim proident id exercitation eiusmod mollit voluptate. Officia non occaecat magna mo.'
]

{ #category : #'canvas drawing-ovals' }
GtCrasherGeneratedAFW >> udxtbuquhAN [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Fugiat n.'
]

{ #category : #'tests - decoding' }
GtCrasherGeneratedAFW >> udxtbuquhBX [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Exercitation occaecat eiusmod tempor laborum in dolor adipiscing laborum aliqua sit dolor do nisi voluptate officia. Mollit est aute adipiscing cillum mollit irure. Ea dolore dolore laboris. Esse exercitation labore cupidatat sint aute adipiscing excepteur ut in est adipiscing dolore. Ex dolore do ut mollit aute irure reprehenderit. Deserunt sint aliqua ut non qui ea dolor fugiat in elit reprehenderit commodo incididunt laborum exercitation reprehenderit. Eu in velit. Non magna. Sit tempor ut pariatur aute iru.'
]

{ #category : #'shared pools' }
GtCrasherGeneratedAFW >> udxtbuquhBY [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna al."
	^ #[236 87 148 20 27 72 50 37 178 155 36 251 2 68 167 126 2 120 217 22 141 126 112 88 117 30 125 116 193 38 100 230 211 158 128 17 98 220 23 99 46 122 211 63 97 208 198 87 218 78 77 237 181 94 16 246 179 73 49 61 229 26 14 133 110 125 156 32 131 183 86 193 80 209 157 154 56 229 9 241 61 140 211 143 114 249 32 82 122 225 53 247 213 221 34 96 105 104 247 229 213 49 175 68 36 122 99 81 124 219 172 80 99 245 134 170 118 4 249 52 48 159 181 145 76 97 53 11 1 24 121 130 68 114 144 99 90 226 70 85 108 181 216 172 40 175]
]

{ #category : #'morphic dependencies' }
GtCrasherGeneratedAFW >> udxtbuquhDM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et d."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Nulla excepteur id dolore nisi consequat exercitation. Occaecat ut tempor. Mollit ipsum fugiat dolor pariatur ut in mollit aliqua eu anim proident. Veniam commodo occaecat elit officia fugiat elit qui nulla. Excepteur ad tempor irure ut. Nostrud commodo voluptate ullamco in qui quis nulla eu consequat ex ipsum est id cupidatat. Pariatur cillum pariatur consequat exercitation anim sed. Reprehenderit ex ut velit consequat do esse nostru.'
]

{ #category : #'tests - arithmetic' }
GtCrasherGeneratedAFW >> udxtbuquhEB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco."
	^ #ydoklbyuvuyzfaymvtklxyjrbupievowfiasgwsq
]

{ #category : #'add class' }
GtCrasherGeneratedAFW >> udxtbuquhFH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e."
	^ onkepbalkcbokq
]

{ #category : #'testing-primitives' }
GtCrasherGeneratedAFW >> udymanbjcsCY [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ."
	^ dkzazggoslj
]

{ #category : #html }
GtCrasherGeneratedAFW >> udymanbjcsFG [
	^ #hvnuztrsnelpymcbiwlwaizywxhrlzpevstpxxw
]

{ #category : #'api - events' }
GtCrasherGeneratedAFW >> udymanbjcsFW [
	"Lorem ipsum dolor sit amet, consectetu."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Dolore amet. Consequat dolore esse esse eu. Sed cillum non nostrud consequat eu ad commodo. Reprehenderit deserunt ad laboris enim dolore do commodo eiusmod eiusmod. Consequat sed non id adipiscing aute. Eiusmod pariatur quis minim et labore voluptate officia. Excepteur ut dolore laborum quis aliqua exercita.'
]

{ #category : #'halo handling' }
GtCrasherGeneratedAFW >> uhgslwDU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ul."
	^ #vdzraxwu
]

{ #category : #history }
GtCrasherGeneratedAFW >> uhgslwF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. U."
	^ abnpgg
]

{ #category : #'tests - sends' }
GtCrasherGeneratedAFW >> uhgslwGK [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru.'
]

{ #category : #'handling transmission' }
GtCrasherGeneratedAFW >> vcygctiqewAB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u."
	^ #[236 87 148 20 27 72 50 37 178 155 36 251 2 68 167 126 2 120 217 22 141 126 112 88 117 30 125 116 193 38 100 230 211 158 128 17 98 220 23 99 46 122 211 63 97 208 198 87 218 78 77 237 181 94 16 246 179 73 49 61 229 26 14 133 110 125 156 32 131 183 86 193 80 209 157 154 56 229 9 241 61 140 211 143 114 249 32 82 122 225 53 247 213 221 34 96 105 104 247 229 213 49 175 68 36 122 99 81 124 219 172 80 99 245 134 170 118 4 249 52 48 159 181 145 76 97 53 11 1 24 121 130 68 114 144 99 90 226 70 85 108 181 216 172 40 175]
]

{ #category : #mocks }
GtCrasherGeneratedAFW >> vcygctiqewCB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation."
	^ #[167 54 94 126 102 11 100 193 166 190 68 232 226 13 214 168 108 92 242 200 24 97 233 52 60 6 210 233 24 204 222 55 98 23 30 184 22 80 191 35 149 149 12 72 201 183 225 8 158 141 224 237 248 183 147 107 131 63 75 44 33 100 172 211 187 97 136 58 110 211 167 254 66 155 116 190 180 102 228 195 128 3 16 131 230 19 66 76 188 44 109 18 49 172 180 52 102 218 47 104 54 38 251]
]

{ #category : #correcting }
GtCrasherGeneratedAFW >> vcygctiqewCR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veni."
	^ #rdkhymduijb
]

{ #category : #'api actions' }
GtCrasherGeneratedAFW >> vcygctiqewCT [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea comm.'
]

{ #category : #'testing - ast mapping' }
GtCrasherGeneratedAFW >> vcygctiqewEA [
	^ #[120 212 165 221 176 57 81 243 193 79 178 135 125 114 83 92 125 128 248 102 138 135 145 171 83 20 7 217 243 84 177 5 227 189 83 171 19 181 159 69 230 159 8 136 168 228 169 116 241 216 159 119 168 10 164 240 244 34 119 23 205 49 251 167 161 32 137 142 117 173 186 170 19 1 191 2 205 227 46 202 71 59 123 180 152 135 226 13 197 108 47 67 18 17 107 105 101 89 103 151 180 34 124 43 79 205 40 93 115 76 186 28 103 5 86 217 231 10 62 33 24 59 229 26 241 69 118 75 149 168 61 123 200 135 238 169 78 228 75 129 103 86 84 239 61 137 203 125 32 154 33 44 44 239 71 114 244 85 134]
]

{ #category : #choosing }
GtCrasherGeneratedAFW >> vcygctiqewL [
	^ ktpehyjzglvdhik
]

{ #category : #'Polymorph-Widgets' }
GtCrasherGeneratedAFW >> vezkamirCE [
	"Lorem ipsum dolor sit amet, consectetur adip."
	^ abnpgg
]

{ #category : #'global events' }
GtCrasherGeneratedAFW >> vezkamirCF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu."
	^ ktpehyjzglvdhik
]

{ #category : #'tests-unselect-index' }
GtCrasherGeneratedAFW >> vezkamirDP [
	^ #exgsogkkkfvcnjbouscwdnpnjdlmptjvn
]

{ #category : #'tests stream' }
GtCrasherGeneratedAFW >> votrzowlufwqrAY [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid."
	^ #rhpkogdtzhg
]

{ #category : #'system-api' }
GtCrasherGeneratedAFW >> votrzowlufwqrBO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute .'
]

{ #category : #debug }
GtCrasherGeneratedAFW >> votrzowlufwqrN [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ma."
	^ abnpgg
]

{ #category : #changes }
GtCrasherGeneratedAFW >> wgidxcxwnvxaDQ [
	^ #[71 98 179 85 2 206 97 178 194 14 39 210 17 202 72 26 129 226 83 105 15 213 84 58 196 166 174 120 195 213 39 250 249 172 227 50 126 11 145 203 224 110 86 193 239 178 83 78 77 120 16 130 88 230 159 5 246 176 17 84 56 161 160 79 79 57 75 96 154 164 188 234]
]

{ #category : #signalling }
GtCrasherGeneratedAFW >> wgidxcxwnvxaEC [
	^ abnpgg
]

{ #category : #'test approximately greater than' }
GtCrasherGeneratedAFW >> wgidxcxwnvxaR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing ."
	^ #lhogyjrbcrhdzbtrmijpidgueobrzibknhhbtughcij
]

{ #category : #'morph-drawing' }
GtCrasherGeneratedAFW >> wqbyvuknkrnjezrBH [
	^ #mvdfzzauqbuwjwzrihiotmgybtrkeybrxwbtezfmstj
]

{ #category : #'tests - indexof' }
GtCrasherGeneratedAFW >> wqbyvuknkrnjezrCZ [
	"Lorem ipsum dolor sit ame."
	^ #fplsyeadrovtegln
]

{ #category : #'moving changes' }
GtCrasherGeneratedAFW >> wqbyvuknkrnjezrFJ [
	^ #[241 136 172 141 123 29 217 25 178 188 75 219 4 188 147 197 69 206 89 97 170 109 252 122 228 11 129 109 242 77 40 224 167 147 184 136 164 244 61 148 37 180 39 231 230 101 57 213 106 33 126 169 40 253 93 185 192 148 61 138 123 32 176 96 223 161 215 99 9 87 32 116 61 173 100 181 252 169 2 172 206 244 34 250 17 231 235 123 82 135 249 11 225 166 149 149 222 92 43 107 185 36 26 177 179 69 93 1 134 92 70 154 184]
]

{ #category : #'testing-henry' }
GtCrasherGeneratedAFW >> xtavecjjkilmAP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
	^ #mjtljxozcxzlxodiqguznfkkprier
]

{ #category : #'script generation' }
GtCrasherGeneratedAFW >> xtavecjjkilmAV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing e."
	^ #[138 170 60 104 18 189 217 95 245 181 63 60 133 160 209 202 90 240 27 2 144 72 27 65 131 108 155 55 225 29 245 190 255 188 86 56 50 153 245 2 201 157 241 177 242 16 3 224 66 144 162 102 187 48 41 65 191 155 39 17 183 180 187 248 173 96 2 204 125 61 208 87 55 159 108 127 33 73 214 65 204 64 186]
]

{ #category : #selected }
GtCrasherGeneratedAFW >> xtavecjjkilmCN [
	"Lorem ipsum dolor sit a."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Exercitation veniam ad ea aute mollit eiusmod commodo ullamco ut sit ut laborum veniam tempor. Sit reprehenderit lorem cupidatat excepteur dolor. Qui nostrud labore occaecat ut culpa cupidatat qui sed. Non consequat commodo. Ut laborum tempor dolor ea commodo in ex laboris enim non in laboris laboris dolor ad incididunt. Quis non sit ex deserunt in non aute. Duis nisi sit laboris duis et dolor enim enim id aute dolore exercitation culpa lorem dolore lore.'
]

{ #category : #'private - updating' }
GtCrasherGeneratedAFW >> xtavecjjkilmDJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qui."
	^ abnpgg
]

{ #category : #'helper methods' }
GtCrasherGeneratedAFW >> xtavecjjkilmDX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Ex minim non cillum labore ex eu anim velit amet anim elit mollit consectetur dolore aliquip laborum ex. Cillum do tempor sed ut pariatur occaecat tempor aute labore excepteur deserunt a.'
]

{ #category : #'accessing editor' }
GtCrasherGeneratedAFW >> xtavecjjkilmEG [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u."
	^ bakdqejdetmi
]

{ #category : #'spec parsing' }
GtCrasherGeneratedAFW >> xtavecjjkilmEP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
	^ #woqkercbwjfguxxgyvoxfurqvquirgwtlsrkhpvhraqqaj
]

{ #category : #'public access' }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpAR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et d."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Nisi dolore voluptate dolore officia pariatur. Irure minim cupidatat mollit nisi esse consequat elit eu sint commodo eu cillum irure nisi sit excepteur occaecat laborum elit. Cillum officia. Minim irure pariatur proident laborum. Irure eiusmod consequat aute culpa reprehenderit in in officia nulla elit. Adipiscing ut laboris ad ullamco velit. Incididunt ut ut anim dolo.'
]

{ #category : #'temporal for remove' }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpAW [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ."
	^ #trsggendhvkgqfttocopsfuex
]

{ #category : #window }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpBD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull."
	^ #uypspm
]

{ #category : #'build items' }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpBR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ."
	^ #[113 140 212 121 241 219 74 158 203 199 250 239 85 250 167 202 216 193 178 10 123 72 168 90 4 90 141 124 199 247 249 33 141 141 243 145 186 32 70 3 220 44 170 2 128 226 113 244 163 153 12 55 112 101 61 147 106 136 155 237 147 70 71 137 147 133]
]

{ #category : #local }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpCU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi."
	^ #[83 204 34 173 164 93 59 171 84 219 227 65 98 253 154 220 5 252 171 73 37 74 89 233 168 131 78 226 65 128 185 152 216 143 98 143 220 29 156 30 200 209 1 99 143 43 41 216 103 96 54 84 36 105 236 87 126 86 52 41 26 168 135 9 150 70 241 15 181 196 93 245 14 8 198 62 87 245 249 186 180 31 24 61 33 73 24 185 55 25 76 117 32 170 135 44 249 174 36 223 185 249 249 75 116 208 209 220 100 130 45 93 49 88 188 156 181 225 19 1 191 219 126 213 130 255 206 126 49 126 242 51 30 199 194 18 38 150 101 76 18 250 11 240 71 231 87 85 121 53 61 23 7 134 2 177 166 23 189 179 13 41 181 194 69 131 139 214 131 165 168 40 222 233 154 44 221 91 99 178 24 189]
]

{ #category : #'construction-defined' }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.."
	^ #[99 159 47 171 200 217 23 172 70 10 122 128 112 84 36 199 113 96 110 69 99 206 214 126 237 4 66 50 50 6 128 195 3 97 68 215 173 204 87 87 191 107 123 249 54 36 25 153 53 107 72 107 140 236 179 167 207 6 171 174 180 13 68 254 60 102 166 89 12 153 236 146 64 21 226 215 182 129 33 134 85 40 205 223 248 151 215 206 151 222 182 221 254 192 231 147 116 26 166 59 45 91 160 101 173 121 75 132 45 102 5 111 110 108 90 205 204 123 94 243 164 130 50 183 178 197 202 39 113 149 132 10 79 202 174 189 70 190 249 178 230 68 61 101 138 254 223 87 200 123 57 122 32 241 3 242 47 228 80 28 228 220 38 101 210 196 194 78]
]

{ #category : #'brick-structure' }
GtCrasherGeneratedAFW >> yaqimgpzsjnygpG [
	^ bakdqejdetmi
]

{ #category : #'tests - public methods' }
GtCrasherGeneratedAFW >> ygfypuneknsvzvBC [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim a."
	^ dkzazggoslj
]

{ #category : #preferences }
GtCrasherGeneratedAFW >> ygfypuneknsvzvBI [
	"Lorem ipsum dolor ."
	^ #jktldypcwkykbqbynz
]

{ #category : #'game controls' }
GtCrasherGeneratedAFW >> ygfypuneknsvzvCH [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco lab.'
]

{ #category : #'bytecode generation' }
GtCrasherGeneratedAFW >> ygfypuneknsvzvDT [
	"Lorem ipsum dolor sit amet,."
	^ #[130 211 137 29 74 78 3 90 108 226 58 184 120 39 40 218 182 183 156 106 70 247 51 83 12 104 190 89 96 116 132 40 179 45 240 128 98 110 87 242 172 84 242 167 221 126 45 6 104 13 217 137 158 223 130 221 92 251 8 245 137 228 188 40 255 8 31 207 102 127 1 87 8 41 19 201 206 78 247 212 168 170 250 244 166 1 138 190 132 203 227 169 154 129 151 73 63 15 40 101 125 158 46 188 123 89 198 62 247 2 22 5 97 223]
]

{ #category : #description }
GtCrasherGeneratedAFW >> ygfypuneknsvzvGH [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation u.'
]

{ #category : #shout }
GtCrasherGeneratedAFW >> zdhbsspqazebAU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut en.'
]

{ #category : #'accessing - cache' }
GtCrasherGeneratedAFW >> zhrfkyA [
	^ ktpehyjzglvdhik
]

{ #category : #'do-its' }
GtCrasherGeneratedAFW >> zhrfkyAC [
	^ #[246 128 209 177 69 106 75 229 27 80 201 164 225 149 23 80 98 231 31 103 203 79 88 43 135 15 230 78 164 165 224 107 74 51 142 43 98 227 55 60 69 143 50 204 8 132]
]

{ #category : #smoothing }
GtCrasherGeneratedAFW >> zhrfkyAM [
	^ onkepbalkcbokq
]

{ #category : #constructor }
GtCrasherGeneratedAFW >> zhrfkyAZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ."
	^ #dqfcclfaisvbbxtdrcwhtrkxdqrplvsdoyhqluswk
]

{ #category : #'canvas drawing-polygons' }
GtCrasherGeneratedAFW >> zhrfkyBG [
	^ #jpwmqhyowdscdjtesusiaqyccvvsaxspvfurfccsuio
]

{ #category : #'reflecive api' }
GtCrasherGeneratedAFW >> zhrfkyCK [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Except.'
]

{ #category : #'tests - handy utils' }
GtCrasherGeneratedAFW >> zhrfkyDS [
	"Lorem ipsum dolor sit ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Pariatur quis magna qui cupidatat non excepteur exercitation ipsum magna. 

Consequat non exercitation ut duis cillum dolore dolor labore nostrud sint occaecat amet nostrud et culpa. Dolor reprehenderit ut irure nulla culpa nisi commodo. Sint id non minim. Ea non et amet in aliqua adipiscing est qui in culpa. Aliquip exercitation lorem eu aute sunt. Sunt eu sunt nostrud ea enim consectetur et dolore. 

Consequat sint do labore fugiat laborum et amet e.'
]

{ #category : #help }
GtCrasherGeneratedAFW >> zhrfkyJ [
	^ #[234 158 198 247 27 98 93 215 4 53 114 137 84 124 144 179 79 252 71 6 14 12 11 254 128 192 81 60 135 89 31 190 101 149 104 176 44 58 33 5 118 194 193 130 244 149 152 151 67 248 197 164 120 127 239 187 223 68 165 227 128 107 223 219 75 105 235 195 56 134 109 76 34 184 229 169 244 251 168 237 10 131 243 221 83 67 196 141 28 169 228 51 72 147 206 168 213 151 136 140 187 120 191 129 7 160 93 17 239 255 103 215 196 76 43 127 34 7 248 79 134 241 181 96 203 140 17 22 248 194 222 247 203 169 152 239 199 121 32 45 2 14 27 28 149 15 250 219 114 56 156 129 52 160 114 88 194 65 93 204 141 40 99 246 10 169 129 161 82 3 128 85 74 153 67 63 87 245 28 101 45 22 60 40 85 19 252 150 132]
]
