Class {
	#name : #GtCrasherGeneratedABI,
	#superclass : #Object,
	#instVars : [
		'kadncvgjxpkspgs',
		'gltuylri',
		'yoxefmedv',
		'zegkmruag',
		'xhzzyzgymplbp',
		'mqekbdxjpl',
		'osozncotmsmt',
		'vxmkirdfsjigzxf',
		'btarkggib',
		'ivbqhytw',
		'tpksqzyjfeet',
		'mcmqluedaqsh',
		'biayal',
		'whorfdobxsnsx',
		'xfthuvfhlw',
		'gpgkcgay'
	],
	#category : #'GToolkit-CrasherGenerated'
}

{ #category : #selected }
GtCrasherGeneratedABI >> alvoplqrqifqAE [
	^ #skoczcmjgziqihkyeukeolxrdnarymcazuwmeuwyujqbxve
]

{ #category : #'tests - operations on MCPackages' }
GtCrasherGeneratedABI >> alvoplqrqifqBF [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut lab."
	^ #wjbtvktasjfuvcwvaqdswudvijhyjwiyqwdlc
]

{ #category : #'brick-tab-label-actions' }
GtCrasherGeneratedABI >> bcjxbpCB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tem."
	^ #[32 35 161 137 44 119 12 3 48 156 47 218 84 20 215 52 61 132 9 125 215 79 40 186 181 52 227 8 165 79 24 159 148 144 134 69 172 191 9 52 29 89 201 25 140 123 103 207 64 166 233 224 138 124 206 49 200 224 2 251 234 251 220 28 171 232 72 157 77 71 141 160 77 220 48 249 117 32 183 163 69 168 171 72 229 243 167 9 139 228 151 113 193 35 87 140 155 210 186 207 169 240 44 71 152 58 221 144 248 36 150 35 35 174 234 45 210 180 215 192 119 15 16 121 102 142 100 208 53 247 235 92 3 125 241 84 16 117 38 155 55 57 134 9 149 75 195 83 112 155 1 165 53 13 168 96 143 224 105 2 73 5 1 121 135 148 116 131 118 45 200 14 23 120 59 1 166]
]

{ #category : #'testing-primitives' }
GtCrasherGeneratedABI >> bcjxbpO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi."
	^ #[247 151 100 26 222 238 127 90 74 252 50 146 190 159 130 145 172 199 28 7 111 85 209 70 88 101 115 25 183 190 111 130 102 222 132 103 11 239 178 157 53 240 193 81 92 212 88 3 75 224 136 214 12 253 122 162 198 150 85 30 211 54 138 168 153 157 125 28 158 26 102 114 147 51 204 69]
]

{ #category : #'tests - copying part of sequenceable' }
GtCrasherGeneratedABI >> budbilseeqjAH [
	^ #ivutomux
]

{ #category : #other }
GtCrasherGeneratedABI >> clmluusopxdkiAZ [
	^ #[89 50 168 118 250 156 18 38 153 66 251 76 17 188 227 217 252 29 133 27 63 190 46 38 113 88 62 212 15 164 218 144 222 144 115 208 251 112 6 251 228 6 102 251 160 247 84 213 181 119 28 131 111 43 112 135 103 197 10 218 115 38 120 234 167 64 57 114 34 224 192 94 140 173 6 1 115 148 113 100 231 105 50 4 216 70 147 232 115 186 84 121 51 212 154 9 119 233 75 110 231 14 49 9 242 74 76 174 89 89 96 89 230 193 111 190 170 57 81 11 244 47 40 228 94 34 216 11 188 189 92 41 109 199 74 231 68 45 46 13 154 132 178 82 49 88 173 101 218 111 49 200 238 8 89 63 93 133 198 180 13 219 148 153 208 59 78]
]

{ #category : #shaping }
GtCrasherGeneratedABI >> clmluusopxdkiBW [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Consequat ut culpa ipsum veniam in velit dolor est reprehenderit anim aliquip aliqua ad occaecat veniam reprehenderit ipsum do ea amet. Sint quis quis consectetur dolor lorem. 

Et aliqua consectetur est mollit ullamco do ut lorem laboris eiusmod tempor fugiat laborum commodo qui laboris adipiscing. Al.'
]

{ #category : #styler }
GtCrasherGeneratedABI >> eqtaviuogtBL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ."
	^ #kojarxgycxcfrfrwwetssfnxqxqccopm
]

{ #category : #'point functions' }
GtCrasherGeneratedABI >> gcjpycgkBB [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Cupidatat mollit ipsum occaecat ea occaecat dolore. Sit nostrud dolore dolor in in. Esse consequat anim dolore ut dolore commodo. Incididunt incididunt irure nulla ut labore sit nostrud veniam incididunt irure est magna aliquip. Quis.'
]

{ #category : #'actions lookup' }
GtCrasherGeneratedABI >> gcjpycgkCN [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Ad cupidatat exercitation do labore. Ex sed in tempor sunt eiusmod magna dolor dolore. 

Duis pariatur do in cupidatat quis anim sint reprehenderit adipiscing non eiusmod dolor sint ut ea consequat dolor magna ex. Exercitation sed qui qui ad cillum sint dolore ut in consectetur. Sit reprehenderit dolore aliquip proident nisi nostrud laborum nostrud magna aliquip. Eiusmod sed nulla ut est enim labore laboris. Ullamco ad esse est laboris sunt ea eiusmod dolor ex qu.'
]

{ #category : #lint }
GtCrasherGeneratedABI >> gsonvcbhllxmCH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .'
]

{ #category : #'setting dashes' }
GtCrasherGeneratedABI >> gyzwpyycyC [
	^ tpksqzyjfeet
]

{ #category : #'tests-basic' }
GtCrasherGeneratedABI >> gzdillrdvwfqmjfAC [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull."
	^ #[44 248 203 51 85 196 138 238 193 231 254 136 118 187 78 96 77 34 90 41 161 84 173 70 26 19 174 79 54 126 61 242 71 108 100 9 151 184 88 24 34 65 2 230 106 90 132 45 169 107 156 106 112 145 138 200 218 254 83 115 147 247 104 162 156 111 26 248 11 92 37 222 104 167 183 207 37 136 180 225 236 89 26 224 83 69 134 150 177 169 238 3 103 84 200 67 189 205 149 151 242 108 123 15 1 125 9 166 45 239 145 196 165 122 236 141 200 26 144 168 40 49 120 211 115 134 63 210 243 45 202 147 62 89 96 172 111 52 42 28 220 218 27 77 225 233]
]

{ #category : #'SUnit-support' }
GtCrasherGeneratedABI >> gzdillrdvwfqmjfBO [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.'
]

{ #category : #results }
GtCrasherGeneratedABI >> gzdillrdvwfqmjfH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e."
	^ #djogsy
]

{ #category : #'add-remove' }
GtCrasherGeneratedABI >> hcjurxijjhyfBJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi u."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ali.'
]

{ #category : #rules }
GtCrasherGeneratedABI >> hcjurxijjhyfBS [
	^ #[169 198 198 148 109 27 129 11 62 217 62 99 105 156 229 108 208 241 90 30 79 39 144 98 188 5 58 229 134 252 140 222 132 10 247 172 25 56 203 163 133 59 78 128 39]
]

{ #category : #undo }
GtCrasherGeneratedABI >> hsmyqaaofsAO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exer."
	^ #[129 103 233 89 91 221 188 117 164 26 73 33 85 133 219 180 27 77 86 146 211 141 252 89 229 178 209 148 98 61 2 103 146 15 255 209 156 105 192 169 51 125 53 56 111 130 32 41 66 149 105 10 50 83 62 93 50 249 19 8 161 88 143 200 173 201 229 14 103 175 159 206 27 175 154 35 247 56 123 117 145 14 39 36 176 103 66 144 5 20 40 92 52 223 56 89 60 118 62 172 4 217 187 1 225 12 208 153 64 187 153 10 146 181 116 109 9 64 125 131 112 33 146 163 142 50 200 158 167 189 62 129 160 255 228 248 128 121 83 61 136 106 118 234 241 99 100 64 228 219 55 214 9 60 77 202 19 139 26 68 160 12 184 35 75 164 191 9 134 178 24 174 88 250 7 188 149 95 96 18]
]

{ #category : #numeric }
GtCrasherGeneratedABI >> hsmyqaaofsU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi."
	^ #oflvluujwexckjmrspfkjd
]

{ #category : #completion }
GtCrasherGeneratedABI >> ilofzaadE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna al."
	^ #[145 173 71 25 25 204 223 21 210 188 246 1 211 66 25 249 10 152 210 9 251 8 32 2 135 2 144 76 219 203 228 33 178 91 84 25 233 5 144 11 63 203 97 177 72]
]

{ #category : #'modifier state' }
GtCrasherGeneratedABI >> imsapnbkkhjokcBG [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut."
	^ yoxefmedv
]

{ #category : #lint }
GtCrasherGeneratedABI >> imsapnbkkhjokcBP [
	^ #kalvdwnijsef
]

{ #category : #'submorphs-accessing' }
GtCrasherGeneratedABI >> jzzugerfskbhmA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Duis quis velit ex laborum. Cons.'
]

{ #category : #proxy }
GtCrasherGeneratedABI >> jzzugerfskbhmAW [
	^ #ljldgtvqpehsmwtreyjxijp
]

{ #category : #'public-testing' }
GtCrasherGeneratedABI >> jzzugerfskbhmBT [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitati."
	^ #[106 216 182 70 232 73 145 203 246 109 134 25 15 100 175 148 150 131 152 3 175 228 91 57 192 145 171]
]

{ #category : #preferences }
GtCrasherGeneratedABI >> jzzugerfskbhmCM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt."
	^ #[13 221 191 203 148 232 182 82 212 62 45 43 227 108 151 247 31 197 34 231 143 87 50 37 222 222 26 210 167 148 86 39 169 98 147 188 94 128 142 66 38 99 208 60 7 111 164 176 42 66 33 175 16 242 16 237 47 159 147 121 52 209 46 193 61 21 79 13 252 20 252 63 112 224 92 78 217 207 61 206 186 90 50 113 197 243 134 119 145 106 122 148 242]
]

{ #category : #'events-shortcuts' }
GtCrasherGeneratedABI >> kmzeejxqornZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magn."
	^ #[146 89 138 116 89 235 11 104 199 82 164 12 59 58 199 127 54 25 54 244 85 204 174 56 125 91 78 208 52 253 132 117 94 238 51 189 213 212 22 248 43 237 202 146 171 14 152 250 197 38 39 159 13 3 112 107 115 33 42 234 218 28 57 72 52 151 92 8 183 34 245 254 172 130 97 136 28 191 110 197 62 226 151 87 30 132 100 110]
]

{ #category : #coverage }
GtCrasherGeneratedABI >> lvyijbhagtnhxAB [
	^ #[61 46 120 179 5 13 16 161 100 130 86 221 47 231 47 1 11 63 152 58 45 204 16 59 248 247 17 88 78 71 97 217 170 166 217 38 204 26 161 192 241 198 65 195 26 72 225 66 183 248 79 10 36 206 203 170 106 39 42 120 85 188 10 192]
]

{ #category : #'widget protocol' }
GtCrasherGeneratedABI >> lvyijbhagtnhxBM [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis no."
	^ #fipxprwekhoaomxkdsjdmwqwseeksbzfcgmydwvqxrqvgraipjieikw
]

{ #category : #'accumulator ops' }
GtCrasherGeneratedABI >> lvyijbhagtnhxX [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proid.'
]

{ #category : #'file paths' }
GtCrasherGeneratedABI >> lzivergntbeoBK [
	^ #[41 192 55 91 140 170 42 167 175 166 91 43 67 79 209 197 58 255 227 145 150 238 145 241 236 146 3 139 160 117 120 1 220 4 93 71 155 196 96 196 13 102 104 152 128 162 56 24 40 160 106 77 133 99 112 66 119 165 6 41 91 155 75 128 107 200 254 160 228 177 247 89 74 163 243 246 14 32 108 82 58 135 199 8 199 225 219 206 205 126 205 75 21 140 36 218 88 94 102 197 198 136 51 132 82 223 162 107 69 240 38 110 56 230]
]

{ #category : #'private-history' }
GtCrasherGeneratedABI >> lzivergntbeoCD [
	^ #[62 55 170 226 10 245 17 105 152 67 10 104 83 143 63 29 140 137 69 79 144 42 172 17 109 47 160 118 134 83 182 169 142 218 206 142 85 251 158 122 22 199 63 250 191 202 113 223 236 192 26 191 76 247 49 178 43 62 153 193 48 8 108 105 208 82 147 26 247 149 201 85 214 146 144 131 156 145 132 96 69 211 223 245 202 192 108 92 124 122 16 223 251 110 65 80 240 207 190 29 66 49 52 151 224 91 78 86 197 208]
]

{ #category : #'tests-Getting Started' }
GtCrasherGeneratedABI >> mzybwdCO [
	^ vxmkirdfsjigzxf
]

{ #category : #'accessing matrices' }
GtCrasherGeneratedABI >> mzybwdI [
	^ #aqgaoslaj
]

{ #category : #'api-valueHolder' }
GtCrasherGeneratedABI >> nrokscidisqkQ [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Fugiat enim do ea ex consequat exercitation tempor non cupidatat esse aliqua exercitation est velit nostrud do. Pariatur adipiscing cillum eu ipsum eu culpa. Nisi fugiat officia ut nisi enim sint ad magna consectetur ullamco ea sint est consequat enim consequat culpa amet laborum incididunt. Culpa id dolore esse do esse voluptate aliqua in dolore in consequat amet .'
]

{ #category : #'guinea pigs' }
GtCrasherGeneratedABI >> ohehituoodBC [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Et nisi dolore aute est veniam laborum nostrud ullamco dolor non cillum veniam officia ad sit. Amet nisi dolor tempor veniam commodo ad pariatur ipsum consequat minim. Officia quis magna ut aute laborum culpa aliquip dolore. Adipiscing laboris in magna qui dolore fugiat officia veniam sed qui occaecat aliqua ad ut eu esse ex voluptate in. Amet reprehenderi.'
]

{ #category : #'private-source' }
GtCrasherGeneratedABI >> ohehituoodBH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, se."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Exercitation magna adipiscing irure cillum non aliquip ut ut ex exercitation. Enim consequat tempor consectetur esse sit pariatur lorem consequat ut nulla duis eu cupidatat cillum cillum aliquip. Consequat amet est cupidatat esse pariatur minim adipiscing amet sint ea sed cillum. Irure laborum. 

Qui dolore ut pariatur occaecat aliqua dolor fugiat ex aliquip officia in est in. Voluptate adipiscing reprehenderit proident non pariatur labore. Laboris in cupidatat qui cillum laborum ex cupidatat mollit ad nulla et inc.'
]

{ #category : #'primitives atomic' }
GtCrasherGeneratedABI >> ohehituoodG [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut lab."
	^ ivbqhytw
]

{ #category : #pillaging }
GtCrasherGeneratedABI >> oioubjBY [
	^ #dcbkrduswkxopmezku
]

{ #category : #'html tags' }
GtCrasherGeneratedABI >> onyxtiAI [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor."
	^ xhzzyzgymplbp
]

{ #category : #'working-directory' }
GtCrasherGeneratedABI >> plzdnbqtdjiehAS [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost."
	^ #nhzikzjbizquesrwlowblzfhpadslkuacctdmwyipdj
]

{ #category : #'taskbar-private' }
GtCrasherGeneratedABI >> plzdnbqtdjiehAV [
	^ xhzzyzgymplbp
]

{ #category : #'event field' }
GtCrasherGeneratedABI >> plzdnbqtdjiehAX [
	^ #pawdeexbqezvdpfmskjmizfvrtmsrpftjxfdsv
]

{ #category : #'freeing resources' }
GtCrasherGeneratedABI >> plzdnbqtdjiehBD [
	"Lorem ipsum dolor sit amet, consectetur adipisci."
	^ #[94 170 244 63 85 215 211 255 87 253 150 254 106 19 7 241 227 115 243 48 225 73 167 100 230 102 175 94 130 137 2 151 20 169 220 121 155 65 125 223 18 9 190 194 252 199 7 116 110 76 183 224 83 14 115 232 217 246 200 171 160 59 36 16 192 89 69 63 46 86 80 231 88 144 110 28 109 193 73 10 118 89 25 1 29 191 84 70 52 40 191 124 255 65 115 114 125 211 248 50 16 214 8 137 146 230]
]

{ #category : #'tabs creation' }
GtCrasherGeneratedABI >> plzdnbqtdjiehS [
	^ #[45 83 108 142 157 188 4 22 130 26 76 110 249 52 102 217 82 187 169 138 126 201 41 199 172 66 199 43 77 90 7 203 144 25 181 91 248 217 188 175 102 167 209 181 3 111 1 241 191 116 213 245 9 229 56 108 227 49 133 67 21 204 155 102 106 118 108 46 155 4 58 82 89 97 212 30 44]
]

{ #category : #'write and read' }
GtCrasherGeneratedABI >> pooignigiqzwfAL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco la."
	^ tpksqzyjfeet
]

{ #category : #'API-changes' }
GtCrasherGeneratedABI >> pooignigiqzwfAN [
	"Lorem ipsum dolor sit amet, consect."
	^ #[29 77 62 23 168 36 200 223 193 75 113 85 74 216 22 219 20 108 125 240 128 142 243 177 239 251 242 106 248 55 11 9 155 110 77 142 132 103 212 130 139 250 171 214 147 125 24 34 238 215 112 118 47 150 150 239 63 180 164 212 94 214 4 27 24 211 38 158 97 42 208 32 118 41 86 235 10 28 144 110 214 40 129 227 223 222 74 230 187 221 253 145 129 115 180 201 243 249 66 146 103 22 9 13 158 253 183 255 242 177 146 251 139 33 77 102 137 113 222 27 24]
]

{ #category : #'text support' }
GtCrasherGeneratedABI >> pooignigiqzwfV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull.'
]

{ #category : #'tests - rpackage' }
GtCrasherGeneratedABI >> pxvkdsgzpudzyCA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nos."
	^ #[238 183 134 74 103 255 211 47 74 151 110 92 174 243 164 140 107 166 63 132 216 242 61 210 159 250 179 226 171 116 5 184 111 126 33 242 81 19 163 212 234 42 203 27 253 167 96 179 100 215 209 179 252 7 115]
]

{ #category : #hierarchy }
GtCrasherGeneratedABI >> pxvkdsgzpudzyN [
	^ #lzwzwxrqwkyuttcxalteeelx
]

{ #category : #'to move to a simple RPackage test case' }
GtCrasherGeneratedABI >> qtguacrahsxR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Quis quis excepteur lorem commodo enim eu laborum deserunt deserunt fugiat eiusmod non reprehenderit proident ullamco. Anim ex enim ad labore veniam nisi in incididunt culpa excepteur sint culpa ad commodo tempor. Dolore culpa velit nulla reprehenderit deserunt lorem aute do eiusmod est anim fugiat. 

Ullamco aliqua tempor eu in ut dolore enim qui magna.'
]

{ #category : #gui }
GtCrasherGeneratedABI >> qylerrxalqtvfqxAG [
	^ #oqjxulbcgkkslpyjyddbr
]

{ #category : #'literal testing' }
GtCrasherGeneratedABI >> qylerrxalqtvfqxF [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sit occaecat amet duis magna consectetur culpa magna commodo in sit quis velit. Tempor consectetur laborum ipsum incididu.'
]

{ #category : #'read/write usage' }
GtCrasherGeneratedABI >> rbswliBV [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Laboris amet dolore cupidatat irure deserunt aliqua c.'
]

{ #category : #'private-geometry' }
GtCrasherGeneratedABI >> rbswliJ [
	^ #[147 106 12 93 47 231 58 72 199 242 149 211 24 40 189 127 168 186 94 100 75 143 145 140 179 212 105 250 218 164 68 59 146 46 216 49 197 126 132 16 10 220 44 110 68 173 254 19 145 209 6 154 208 110 59 71 170 125 118 111 142 152 166 233 207 54 114 130 189 84 253 135 10 160 66 136 69 70 193 97 233 160 129 6 78 82 101 107 233 185 158 178 186 102 109 157 173 46 14 101 148 65 36 140 171 103 20 149 128 1 63 96 4 87 65 192 39 148 47 239 123 141 70 69 27 151]
]

{ #category : #types }
GtCrasherGeneratedABI >> rkusjpwofubpvutAD [
	^ #[200 186 65 187 88 119 30 241 36 168 209 223 146 228 178 16 13 55 53 4 35 63 197 196 182 182 184 217 74]
]

{ #category : #releasing }
GtCrasherGeneratedABI >> smlawslmtbloAJ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Duis pariatur cupidatat officia reprehenderit officia do esse. Sed enim ea dolore voluptate reprehenderit aliqua commodo occaecat laboris dolor tempor quis lorem in ea labore ut dolor culpa. Ut nostrud do labore eu culpa officia ut officia labore ipsum in veniam deserunt culpa exercitation. Do sit duis reprehenderit et dolore aliqua deserunt ex culpa nostrud aliqua aliquip. Ut ad dolor nisi enim. Quis pariatur id commodo velit ad ut veniam aliquip veniam ea do do quis dolor sed non in incididunt et..'
]

{ #category : #'managing line numbers' }
GtCrasherGeneratedABI >> smlawslmtbloAM [
	^ xfthuvfhlw
]

{ #category : #'Issue 154' }
GtCrasherGeneratedABI >> smlawslmtbloCJ [
	^ #[133 223 7 183 91 30 80 184 59 71 44 120 151 52 2 53 54 192 174 12 60 14 157 237 205 17 232 76 109 247 133 35 134 137 166 28 8 204 158 82 129 151 31 13 155 68 110 100 142 218 35 230 142 219 169 167 194 30 180 197 175 130 9 150 69 94 196 140 87 177 32 131 199 186 58 7 129 213 20 125 11 81 194 92 227 107 95 184 115 28 206 77 24 141 11 17 1 85 62 147 182 160]
]

{ #category : #'private-class var' }
GtCrasherGeneratedABI >> smlawslmtbloY [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sunt consectetur ad ullamco ullamco ad eiusmod adipiscing officia ex est id proident et consectetur ullamco cupidatat dolor sint exercitation. Do dolor est dolore in consectetur dolor dolor pariatur. Ut labore ullamco non aliquip officia dolore ut minim in cupidatat. Nulla non culpa ea id aliquip in non ex pariatur dolor excepteur elit esse exercitation sunt. Ipsum aliqua in in nulla ex mollit do do esse minim magna in. Et offici.'
]

{ #category : #dragging }
GtCrasherGeneratedABI >> tbzwaijofoerAY [
	^ vxmkirdfsjigzxf
]

{ #category : #'accessing-ui' }
GtCrasherGeneratedABI >> tlimhfvupwvAQ [
	^ #[48 176 181 254 189 22 200 173 3 97 229 184 43 26 247 149 217 156 155 188 22 172 61 124 80 249 153 63 222 182 241 220 207 131 73 197 251 106 165 207 137 82 165 88 95 25 238 30 228 7 20 251 241 37 147 137 229 19 162 117 146 55 118 37 75 73 215 250 85 144 203 126 176 27 111 167 135 186 1 199 233 204 44 218]
]

{ #category : #'tests - unsubscribing' }
GtCrasherGeneratedABI >> tlimhfvupwvCC [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Officia cupidatat ut lorem culpa ut sint veniam excepteur id aute commodo veniam sunt tempor. Excepteur laborum est. 

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris .'
]

{ #category : #'manage scrolling' }
GtCrasherGeneratedABI >> tlimhfvupwvT [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit."
	^ #[50 109 55 87 102 74 220 19 158 57 71 4 241 90 235 234 29 15 60 239 47 8 25 54 27 93 2 251 36 101 5 202 115 251 186 153 195 65 254 143 212 194 171 90 122 106 166 157 170 185 110 242 141 35 128 204 146 152 5 25 66 56 212 47 20 213 204 43 209 105 198 209 41 156 109 94 184 188 218 111 47 209 232 149 97 144 87 112 251 6 160 223 117 16 231 24 87 138 113 218 29 119 179 236 193 251 235 189 174 212 198 27 142 247 139 7 179 141 59 51 178 213 112 16 21 184 219 130 50 63 151 133 49 204 226 20 63 155 80 47 251 221 44 136 151 222 143 91 54 63 112 197 143 89 182 123 79 226 169 67 102 18 157 186 52 141 62 199 206 180 19]
]

{ #category : #'parsing-large int' }
GtCrasherGeneratedABI >> udxtbuquhBQ [
	"Lorem ipsum dolor sit."
	^ #[134 253 195 143 252 20 199 254 145 127 14 145 162 224 19 134 43 19 55 51 224 9 73 232 177 237 2 81 67 16 146 191 63 10 146 128 23 50 30 89 84 36 179 131 227 104 83 77 84 71 223 78 189 196 113 85 119 83 146 196 45 246 79 194 171 21 126 138 164 161 229 155 11 139 165 82 225 92 90 180 121 12 178 107 192 141 25 77 60 53 196 183 80 77 194 149 73 97 128 89 223 106 184 117 254 152 136 254 80 75]
]

{ #category : #context }
GtCrasherGeneratedABI >> udxtbuquhBR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa q.'
]

{ #category : #evaluation }
GtCrasherGeneratedABI >> udxtbuquhBZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq."
	^ #[36 116 87 108 237 157 187 21 55 161 98 192 125 128 9 48 100 214 189 18 31 28 217 25 33 48 4 138 221 36 114 54 188 9 75 71 119 139 119 106 37 194 89 227 93 120 118 251 4 16 15 168 160 128 37 44 98 230 164 169 37 118 109 156 29 197 244 43 130 104 59 200 28 10 104 135 60 5 179 237 254 233 22 25 124 138 81 79 184 47 62 231 18 96 182 31 162 133 234 244 230 223 238 236 243 223 36 191 189 180 183 39 224 2 175]
]

{ #category : #'popup - listeners' }
GtCrasherGeneratedABI >> udxtbuquhCG [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore m."
	^ #deacmeelejjnydcxvkr
]

{ #category : #'querying-github' }
GtCrasherGeneratedABI >> udymanbjcsAF [
	"Lorem ipsum dolor sit amet, consectetu."
	^ #gqlhkpgy
]

{ #category : #'canvas drawing-text' }
GtCrasherGeneratedABI >> uhgslwAA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et ."
	^ #[19 211 192 148 125 45 148 181 177 63 155 44 240 150 202 32 133 231 20 175 60 79 172 123 169 250 124 20 100 59 226 143 87 213 25 202 222 183 80 197 223 9 228 119 172 7 152 59 232 151 103 102 106 67 35 36 78 44 200 220 29 100 38 168 151 164 145 55 69 193 179 93 169 54 224 114 29 79 18 64 194 167 149 102 11 171 57 155 240 38 227 113 183 120 127 30 48 100 66 241 88 64 99 154 44 119 170 83 74 210 55 66 207 69 70 45 219 149 139 173 80 18 98 85 120 255 10 120 25 171 92 143 13 28 195 78 128 197 72 253 168 59 105 16 166 106 9 188 58 84 16 45 139 175]
]

{ #category : #modifying }
GtCrasherGeneratedABI >> uhgslwAP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem nulla amet sit sit occaecat cillum. Ad ut ut qui consequat incididunt ea ut ipsum ut commodo. Culpa eu adi.'
]

{ #category : #hooks }
GtCrasherGeneratedABI >> uhgslwK [
	^ mqekbdxjpl
]

{ #category : #doits }
GtCrasherGeneratedABI >> vcygctiqewCI [
	^ biayal
]

{ #category : #statistics }
GtCrasherGeneratedABI >> vezkamirBU [
	^ whorfdobxsnsx
]

{ #category : #'tests object' }
GtCrasherGeneratedABI >> vezkamirCL [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conseq.'
]

{ #category : #'brick-tab-label' }
GtCrasherGeneratedABI >> vezkamirCP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ."
	^ #[73 16 148 103 95 218 154 104 1 71 58 11 152 148 112 13 166 106 83 117 20 168 125 214 71 136 90 91 196 178 40 91 197 157 124 159 242 221 74 73 149 52 21 142 108 29 126 86 252 26 196 118 163 192 215 29 132 204 135 242 234 160 171 237 95 210 48 177 9 63 91 240 148 47 173 100 92 187 225 138 147 95 68 108 227 123 162 223 188 184 59 250 202 28 114 85]
]

{ #category : #'accessing menu' }
GtCrasherGeneratedABI >> vezkamirM [
	^ #oriquwdknnbvcnznojrxnhjjimtjzxrxreextdgvyifyuyiukerdme
]

{ #category : #private }
GtCrasherGeneratedABI >> vezkamirP [
	^ #[172 155 159 16 46 237 126 195 83 92 99 35 60 22 36 62 4 19 233 51 98 51 158 225 224 218 223 14 103 133 213 101 112 160 62 7 149 128 7 68 170 225 253 183 115 25 228 140 151 86 83 60 73 129 209 228 248 187 137 209 12 186 161 60 199 254 55 34 174 122 2 124 32 105 174 28 29 22 152 143 212 30 117 49 248 52 25 37 225 158 64 130 201 145 154 63 82 32 28 185 210 3 246 149 46 98 84 13 63 216 39 232 139 34 152 187 160 115 206 206 250 157 191 45 73 103 190 76 239 65 211 172 147 238 97 224 184 196 209]
]

{ #category : #'tests-manual' }
GtCrasherGeneratedABI >> vezkamirW [
	^ xhzzyzgymplbp
]

{ #category : #'tests-streams-compatibility' }
GtCrasherGeneratedABI >> votrzowlufwqrBX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ul.'
]

{ #category : #'gesture detection' }
GtCrasherGeneratedABI >> wgidxcxwnvxaAR [
	^ #[176 163 149 122 35 82 143 141 105 245 236 18 123 109 121 33 109 194 207 134 216 93 205 168 249 111 161 72 249 68 185 196 180 35 234 223 214 230 237 172 104 45 68 155 78 147 180 144 77 113 31 194 163]
]

{ #category : #'queries - behaviors' }
GtCrasherGeneratedABI >> wqbyvuknkrnjezrB [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull."
	^ #[191 79 121 163 122 192 41 198 16 242 107 7 143 202 216 55 1 19 253 55 110 86 185 61 167 212 118 148 254 79 13 202 81 89]
]

{ #category : #'rendering presentations' }
GtCrasherGeneratedABI >> wqbyvuknkrnjezrBE [
	^ #ulewyfyqxlrvkddamyxsjpbpnaggeyisznjfm
]

{ #category : #intializing }
GtCrasherGeneratedABI >> xtavecjjkilmBN [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut en."
	^ #nemewbbusyax
]

{ #category : #'test compiled method' }
GtCrasherGeneratedABI >> xtavecjjkilmD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu."
	^ #[132 162 59 116 245 69 255 104 113 232 203 117 52 72 86 123 36 235 66 151 89 192 253 18 13 12 76 2 241 66 158 29 4 152 194 77 181 13 48 84 231 161 157 92 82 76 59 9 155 25 84 76 187 19 183 178 11 164 129 160 172 100 170 168 177 227 49 15 157]
]

{ #category : #'code execution' }
GtCrasherGeneratedABI >> yaqimgpzsjnygpAU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ."
	^ biayal
]

{ #category : #'pango-options' }
GtCrasherGeneratedABI >> ygfypuneknsvzvAK [
	^ #irhrylshutktoyzampkjlnj
]

{ #category : #'signaling-default' }
GtCrasherGeneratedABI >> ygfypuneknsvzvAT [
	^ #lvsxvzxwslvnnycsmlpntygyodkairllqicyvawjkclalzz
]

{ #category : #'shortcuts installation' }
GtCrasherGeneratedABI >> ygfypuneknsvzvCE [
	^ kadncvgjxpkspgs
]

{ #category : #'private-functions' }
GtCrasherGeneratedABI >> ygfypuneknsvzvL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt."
	^ #[183 101 47 11 6 36 88 118 164 29 74 215 94 218 194 89 186 206 199 222 29 128 68 73 214 249 166 39 209 163 93 31 193 172 43 102 68 156 146 42 99 41 32 26 31 145 204 160 105 25 29 111 22 55 120 15 244 167 215 141 202 97 144]
]

{ #category : #intialization }
GtCrasherGeneratedABI >> zdhbsspqazebBA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut lab."
	^ osozncotmsmt
]

{ #category : #'testing-matching' }
GtCrasherGeneratedABI >> zdhbsspqazebCF [
	^ #ltmwbajvbsjvmrwcypxmz
]

{ #category : #patching }
GtCrasherGeneratedABI >> zhrfkyBI [
	^ #[140 34 153 206 96 124 228 126 131 10 66 11 204 186 61 19 8 237 19 198 115 100 131 105 190 198 87 5 65 185 207 30 229]
]

{ #category : #async }
GtCrasherGeneratedABI >> zhrfkyCK [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo."
	^ tpksqzyjfeet
]
